insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (1, 'B60605', 'Alfred H. Baumann Free Public Library (West Paterson)', '617 Merrick Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (2, 'B84029', 'Anthony Pio Costa Memorial Library (Fairfield)', '64268 Northport Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (3, 'B64688', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '32601 Vermont Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (4, 'B54025', 'Otto Bruyns Public Library (Northfield)', '455 Toban Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (5, 'B94721', 'Carney’s Point Public Library (Penns Grove)', '518 Mockingbird Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (6, 'B44519', 'Clarence Dillon Public Library (Bedminster Far Hills)', '7 Troy Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (7, 'B79366', 'William E. Dermody Public Library (Carlstadt)', '37678 Kim Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (8, 'B48872', 'Clarence Dillon Public Library (Bedminster Far Hills)', '6447 Hauk Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (9, 'B23241', 'Dixon Homestead Library (Dumont)', '3 Vermont Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (10, 'B50687', 'Dowdell Library of South Amboy (South Amboy)', '578 Westerfield Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (11, 'B12294', 'Dwight D. Eisenhower Library (Totowa)', '24850 Monterey Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (12, 'B93254', 'Marie Fleche Memorial Library (Berlin)', '7665 Novick Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (13, 'B67435', 'Franklin Township Free Public Library (Gloucester)', '928 Dorton Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (14, 'B26197', 'Franklin Township Free Public Library (Somerset)', '86374 Del Sol Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (15, 'B33356', 'Free Public Library of Audubon (Audubon)', '1 Esker Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (16, 'B82016', 'Free PL of The Borough of Pompton Lakes (Pompton Lakes)', '0393 Bayside Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (17, 'B84048', 'Gill Memorial Library (Paulsboro)', '3756 Karstens Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (18, 'B81239', 'Margaret E. Heggan Free PL (Washington Twp Gloucester)', '56669 Chinook Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (19, 'B28002', 'Dixon Homestead Library (Dumont)', '35 Browning Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (20, 'B76714', 'James H. Johnson Memorial Library (Deptford)', '85 Merchant Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (21, 'B97763', 'Johnson Public Library (Hackensack)', '3956 Victoria Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (22, 'B65304', 'James H. Johnson Memorial Library (Deptford)', '0 Barby Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (23, 'B84218', 'John F. Kennedy Memorial Library (Wallington)', '550 Beilfuss Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (24, 'B34201', 'Joint Free Public Library of the Chathams (Chatham)', '39776 Oneill Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (25, 'B34811', 'Joint Free PL of Morristown & Morris Twp (Morristown-Morris Twp)', '3045 Fordem Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (26, 'B03737', 'Sally Stretch Keen Memorial Library (Vincentown)', '933 Johnson Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (27, 'B98018', 'John F. Kennedy Memorial Library (Wallington)', '28 Thompson Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (28, 'B80945', 'Lee Memorial Library (Allendale)', '96 Toban Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (29, 'B93320', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '8 Jenifer Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (30, 'B87283', 'Margare E. Heggan Free PL (Washington Twp Gloucester)', '311 Hintze Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (31, 'B11616', 'Marie Fleche Memorial Library (Berlin)', '8 Crowley Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (32, 'B11960', 'Maurice M. Pine Free Public Library (Fair Lawn)', '3 Old Shore Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (33, 'B26589', 'McCowan Memorial Library (Pitman)', '78660 Warbler Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (34, 'B48036', 'Monroe Township Free Public Library (Gloucester Co)', '7 Pine View Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (35, 'B86161', 'Monroe Township Public Library (Middlesex Co.)', '1964 Arizona Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (36, 'B13998', 'Oceanic Free Library (Rumson)', '6 Judy Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (37, 'B43613', 'Otto Bruyns Public Library (Northfield)', '4173 Erie Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (38, 'B31201', 'Maurice M. Pine Free Public Library (Fair Lawn)', '7 Pankratz Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (39, 'B72371', 'Worth Pinkham Memorial Library (Ho-Ho-Kus)', '8 Village Green Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (40, 'B03761', 'Anthony Pio Costa Memorial Library (Fairfield)', '748 Rutledge Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (41, 'B76954', 'Ridgefield Free Public Library (Ridgefield)', '27805 American Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (42, 'B07777', 'Ridgefield Park Free Public Library (Ridgefield Park)', '47471 Lindbergh Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (43, 'B07570', 'Ruth L. Rockwood Memorial Library (Livingston)', '137 Browning Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (44, 'B46504', 'Sally Stretch Keen Memorial Library (Vincentown)', '10894 Muir Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (45, 'B14505', 'Union Free Public Library (Friberger Park', '274 Tomscot Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (46, 'B66809', ' Union NJ)', '5 Ridgeway Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (47, 'B08904', 'Veteran’s Memorial Library (Roselle Park)', '07 Carpenter Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (48, 'B50533', 'W.H. Walters Free Public Library (Alpha)', '10052 Eliot Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (49, 'B06973', 'Wanaque Borough Free Public Library', '7345 Park Meadow Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (50, 'B81013', 'Washington Public Library (Washington Boro/Warren Co)', '34 Randy Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (51, 'B64396', 'Washington Twp Free Public Library (Long Valley/Morris Co)', '2 Mccormick Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (52, 'B98143', 'Washington Twp Public Library (Westwood/Bergen Co)', '597 Mitchell Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (53, 'B33665', 'Whippanong Library Association (Whippany /Hanover Twp)', '4030 Towne Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (54, 'B36548', 'William E. Dermody Public Library (Carlstadt)', '9 Tomscot Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (55, 'B20302', 'Wood-Ridge Memorial Library', '0 Lotheville Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (56, 'B55082', 'Woodstown-Pilesgrove Library', '07615 Pankratz Way');
