insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (1, 'B20531', 'Alfred H. Baumann Free Public Library (West Paterson)', '053 Bartelt Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (2, 'B08662', 'Anthony Pio Costa Memorial Library (Fairfield)', '93 Clemons Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (3, 'B80959', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '1597 Golf Course Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (4, 'B10489', 'Otto Bruyns Public Library (Northfield)', '53 Ridge Oak Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (5, 'B05053', 'Carney’s Point Public Library (Penns Grove)', '54 Melvin Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (6, 'B82878', 'Clarence Dillon Public Library (Bedminster Far Hills)', '578 Forest Run Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (7, 'B05728', 'William E. Dermody Public Library (Carlstadt)', '7 Johnson Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (8, 'B65440', 'Clarence Dillon Public Library (Bedminster Far Hills)', '72 Mifflin Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (9, 'B88152', 'Dixon Homestead Library (Dumont)', '85667 Barby Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (10, 'B85340', 'Dowdell Library of South Amboy (South Amboy)', '1 Hoepker Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (11, 'B24019', 'Dwight D. Eisenhower Library (Totowa)', '51815 Carey Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (12, 'B38408', 'Marie Fleche Memorial Library (Berlin)', '1785 Bartillon Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (13, 'B05927', 'Franklin Township Free Public Library (Gloucester)', '49 Schlimgen Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (14, 'B49009', 'Franklin Township Free Public Library (Somerset)', '15 Everett Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (15, 'B22021', 'Free Public Library of Audubon (Audubon)', '23 Mifflin Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (16, 'B98805', 'Free PL of The Borough of Pompton Lakes (Pompton Lakes)', '3 Ohio Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (17, 'B67887', 'Gill Memorial Library (Paulsboro)', '11 Twin Pines Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (18, 'B74191', 'Margaret E. Heggan Free PL (Washington Twp Gloucester)', '71 Pond Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (19, 'B97385', 'Dixon Homestead Library (Dumont)', '66 Weeping Birch Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (20, 'B88085', 'James H. Johnson Memorial Library (Deptford)', '99598 Heath Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (21, 'B95726', 'Johnson Public Library (Hackensack)', '640 Coolidge Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (22, 'B07846', 'James H. Johnson Memorial Library (Deptford)', '4 Holy Cross Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (23, 'B28860', 'John F. Kennedy Memorial Library (Wallington)', '7811 8th Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (24, 'B31397', 'Joint Free Public Library of the Chathams (Chatham)', '5677 Mccormick Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (25, 'B91436', 'Joint Free PL of Morristown & Morris Twp (Morristown-Morris Twp)', '6605 Ridgeway Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (26, 'B11983', 'Sally Stretch Keen Memorial Library (Vincentown)', '591 Spaight Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (27, 'B22159', 'John F. Kennedy Memorial Library (Wallington)', '8 Gulseth Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (28, 'B17957', 'Lee Memorial Library (Allendale)', '7720 5th Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (29, 'B66707', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '174 Ruskin Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (30, 'B26830', 'Margare E. Heggan Free PL (Washington Twp Gloucester)', '07 Pleasure Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (31, 'B70757', 'Marie Fleche Memorial Library (Berlin)', '56 Pine View Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (32, 'B66096', 'Maurice M. Pine Free Public Library (Fair Lawn)', '14 Maple Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (33, 'B07499', 'McCowan Memorial Library (Pitman)', '031 Londonderry Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (34, 'B11221', 'Monroe Township Free Public Library (Gloucester Co)', '999 Stang Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (35, 'B54857', 'Monroe Township Public Library (Middlesex Co.)', '95164 Cambridge Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (36, 'B64039', 'Oceanic Free Library (Rumson)', '3 Hagan Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (37, 'B66112', 'Otto Bruyns Public Library (Northfield)', '5 Cardinal Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (38, 'B12779', 'Maurice M. Pine Free Public Library (Fair Lawn)', '1 1st Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (39, 'B82755', 'Worth Pinkham Memorial Library (Ho-Ho-Kus)', '6 Florence Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (40, 'B28744', 'Anthony Pio Costa Memorial Library (Fairfield)', '6 Vera Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (41, 'B96882', 'Ridgefield Free Public Library (Ridgefield)', '47 Eagan Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (42, 'B78245', 'Ridgefield Park Free Public Library (Ridgefield Park)', '52 Lyons Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (43, 'B65162', 'Ruth L. Rockwood Memorial Library (Livingston)', '6407 Melvin Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (44, 'B82933', 'Sally Stretch Keen Memorial Library (Vincentown)', '02 Carioca Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (45, 'B41625', 'Union Free Public Library (Friberger Park', '8910 Farragut Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (46, 'B65558', ' Union NJ)', '25551 American Ash Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (47, 'B70959', 'Veteran’s Memorial Library (Roselle Park)', '4 Lunder Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (48, 'B95080', 'W.H. Walters Free Public Library (Alpha)', '1412 Monterey Trail');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (49, 'B22183', 'Wanaque Borough Free Public Library', '76 Karstens Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (50, 'B33531', 'Washington Public Library (Washington Boro/Warren Co)', '93885 Rutledge Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (51, 'B18852', 'Washington Twp Free Public Library (Long Valley/Morris Co)', '363 Manufacturers Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (52, 'B96189', 'Washington Twp Public Library (Westwood/Bergen Co)', '145 Miller Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (53, 'B68421', 'Whippanong Library Association (Whippany /Hanover Twp)', '19 Kensington Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (54, 'B80325', 'William E. Dermody Public Library (Carlstadt)', '3174 Lotheville Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (55, 'B04036', 'Wood-Ridge Memorial Library', '58837 Bay Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (56, 'B45819', 'Woodstown-Pilesgrove Library', '814 Alpine Street');
