insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (1, 'B11162', 'Alfred H. Baumann Free Public Library (West Paterson)', '536 Hallows Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (2, 'B65867', 'Anthony Pio Costa Memorial Library (Fairfield)', '33 Buell Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (3, 'B39767', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '88857 Bartillon Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (4, 'B89281', 'Otto Bruyns Public Library (Northfield)', '91136 Toban Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (5, 'B24264', 'Carney’s Point Public Library (Penns Grove)', '4 Paget Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (6, 'B63121', 'Clarence Dillon Public Library (Bedminster Far Hills)', '1 Hallows Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (7, 'B01458', 'William E. Dermody Public Library (Carlstadt)', '6 Hoepker Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (8, 'B17468', 'Clarence Dillon Public Library (Bedminster Far Hills)', '593 Southridge Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (9, 'B27776', 'Dixon Homestead Library (Dumont)', '22 Starling Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (10, 'B18048', 'Dowdell Library of South Amboy (South Amboy)', '496 Westend Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (11, 'B67482', 'Dwight D. Eisenhower Library (Totowa)', '26745 Elmside Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (12, 'B23477', 'Marie Fleche Memorial Library (Berlin)', '4391 Schlimgen Hill');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (13, 'B65454', 'Franklin Township Free Public Library (Gloucester)', '60589 New Castle Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (14, 'B28458', 'Franklin Township Free Public Library (Somerset)', '57 Drewry Pass');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (15, 'B36313', 'Free Public Library of Audubon (Audubon)', '1 Prentice Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (16, 'B17476', 'Free PL of The Borough of Pompton Lakes (Pompton Lakes)', '63240 Pankratz Drive');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (17, 'B07136', 'Gill Memorial Library (Paulsboro)', '474 High Crossing Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (18, 'B07627', 'Margaret E. Heggan Free PL (Washington Twp Gloucester)', '6717 Rowland Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (19, 'B76349', 'Dixon Homestead Library (Dumont)', '58 Ronald Regan Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (20, 'B85073', 'James H. Johnson Memorial Library (Deptford)', '916 Jenifer Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (21, 'B25544', 'Johnson Public Library (Hackensack)', '896 Del Sol Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (22, 'B17163', 'James H. Johnson Memorial Library (Deptford)', '05353 Dawn Avenue');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (23, 'B09372', 'John F. Kennedy Memorial Library (Wallington)', '8938 Derek Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (24, 'B90217', 'Joint Free Public Library of the Chathams (Chatham)', '86273 Loftsgordon Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (25, 'B12717', 'Joint Free PL of Morristown & Morris Twp (Morristown-Morris Twp)', '68 Superior Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (26, 'B88917', 'Sally Stretch Keen Memorial Library (Vincentown)', '9187 Carey Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (27, 'B80777', 'John F. Kennedy Memorial Library (Wallington)', '9 Luster Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (28, 'B56300', 'Lee Memorial Library (Allendale)', '977 Dahle Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (29, 'B12705', 'Louis Bay 2nd Library and Community Center (Hawthorne)', '93 Maryland Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (30, 'B47328', 'Margare E. Heggan Free PL (Washington Twp Gloucester)', '36215 Ilene Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (31, 'B55452', 'Marie Fleche Memorial Library (Berlin)', '6875 Anthes Lane');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (32, 'B12509', 'Maurice M. Pine Free Public Library (Fair Lawn)', '6166 Springview Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (33, 'B27428', 'McCowan Memorial Library (Pitman)', '280 Tony Junction');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (34, 'B87462', 'Monroe Township Free Public Library (Gloucester Co)', '02 Nancy Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (35, 'B36543', 'Monroe Township Public Library (Middlesex Co.)', '32316 Grim Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (36, 'B81810', 'Oceanic Free Library (Rumson)', '5 Towne Circle');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (37, 'B22318', 'Otto Bruyns Public Library (Northfield)', '51 Arkansas Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (38, 'B53346', 'Maurice M. Pine Free Public Library (Fair Lawn)', '23250 Gateway Terrace');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (39, 'B80555', 'Worth Pinkham Memorial Library (Ho-Ho-Kus)', '379 Lotheville Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (40, 'B46442', 'Anthony Pio Costa Memorial Library (Fairfield)', '4284 Bowman Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (41, 'B35260', 'Ridgefield Free Public Library (Ridgefield)', '18 Morrow Way');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (42, 'B98310', 'Ridgefield Park Free Public Library (Ridgefield Park)', '7178 Macpherson Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (43, 'B39965', 'Ruth L. Rockwood Memorial Library (Livingston)', '758 Fallview Parkway');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (44, 'B96126', 'Sally Stretch Keen Memorial Library (Vincentown)', '357 Loomis Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (45, 'B73321', 'Union Free Public Library (Friberger Park', '4 Sutteridge Road');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (46, 'B76046', ' Union NJ)', '7626 Melvin Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (47, 'B95571', 'Veteran’s Memorial Library (Roselle Park)', '175 Merrick Street');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (48, 'B85241', 'W.H. Walters Free Public Library (Alpha)', '8031 Nobel Park');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (49, 'B21707', 'Wanaque Borough Free Public Library', '9 Northland Alley');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (50, 'B46517', 'Washington Public Library (Washington Boro/Warren Co)', '9 Gateway Center');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (51, 'B95019', 'Washington Twp Free Public Library (Long Valley/Morris Co)', '3321 Logan Court');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (52, 'B76111', 'Washington Twp Public Library (Westwood/Bergen Co)', '26767 Jay Plaza');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (53, 'B37298', 'Whippanong Library Association (Whippany /Hanover Twp)', '21 Londonderry Crossing');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (54, 'B87791', 'William E. Dermody Public Library (Carlstadt)', '74 Thierer Place');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (55, 'B90814', 'Wood-Ridge Memorial Library', '304 Cottonwood Point');
insert into BIBLIOTECA (biblioteca_id, clave, nombre, direccion) values (56, 'B66493', 'Woodstown-Pilesgrove Library', '4939 Northport Park');
