insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (1, 'Josselyn', 'Gorgen', 'Callacher', '58-661-9318', 'jcallacher0@google.nl', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (2, 'Bentlee', 'Doeg', 'Corfield', '20-716-3217', 'bcorfield1@discovery.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (3, 'Pieter', 'Lohrensen', 'Blackborow', '44-913-3256', 'pblackborow2@delicious.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (4, 'Bay', 'Stork', 'Donovin', '46-660-8218', 'bdonovin3@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (5, 'Sande', 'Longwood', 'Tigwell', '73-697-5697', 'stigwell4@java.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (6, 'Wiatt', 'Piolli', null, '75-736-6388', 'wmckeurtan5@ustream.tv', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (7, 'Karol', 'Adenot', 'Founds', '82-606-5979', 'kfounds6@craigslist.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (8, 'Adora', 'Petch', null, '25-195-4390', 'abiford7@umn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (9, 'Herculie', 'Blundell', null, '02-868-2003', 'hnussey8@oakley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (10, 'Karleen', 'Hillock', null, '40-419-4123', 'kfranssen9@amazon.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (11, 'Doe', 'Vercruysse', 'Eakly', '62-607-0563', 'deaklya@ucla.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (12, 'Nikkie', 'Lamy', 'Rodda', '31-000-9440', 'nroddab@furl.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (13, 'Hermine', 'Vosper', 'Calafato', '48-988-0466', 'hcalafatoc@linkedin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (14, 'Nanice', 'Bernini', 'Peracco', '65-879-3202', 'nperaccod@usatoday.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (15, 'Benedick', 'Dell''Abbate', 'Joddens', '85-264-5094', 'bjoddense@stumbleupon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (16, 'Latrena', 'Cornelis', 'Marrill', '84-011-2237', 'lmarrillf@artisteer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (17, 'Loralie', 'Brydie', null, '71-162-5268', 'lguddeg@mashable.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (18, 'Vikky', 'Fredi', 'Swindon', '09-469-3367', 'vswindonh@engadget.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (19, 'Essy', 'Goodman', 'Drakes', '33-821-2941', 'edrakesi@dyndns.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (20, 'Garfield', 'Ramsier', 'Sturley', '19-068-4912', 'gsturleyj@weibo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (21, 'Ana', 'Rameau', 'Wolsey', '56-581-4866', 'awolseyk@nbcnews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (22, 'Charo', 'Renfield', 'Yuryev', '54-640-4546', 'cyuryevl@surveymonkey.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (23, 'Sharity', 'Castiglione', null, '84-265-1588', 'sgianullim@ucoz.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (24, 'Alleyn', 'Sybbe', 'Eyrl', '47-162-6261', 'aeyrln@house.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (25, 'Derward', 'Gimenez', 'Beastall', '43-543-0919', 'dbeastallo@globo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (26, 'Wayne', 'Gelland', 'Patrie', '22-055-3211', 'wpatriep@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (27, 'Esta', 'Falk', 'Laverenz', '23-031-7917', 'elaverenzq@zimbio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (28, 'Dorothea', 'McAllan', null, '83-321-8685', 'dculshewr@oracle.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (29, 'Ellie', 'Troker', 'Phythien', '47-208-4240', 'ephythiens@mtv.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (30, 'Raine', 'Sapsed', 'Streater', '04-857-4437', 'rstreatert@squidoo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (31, 'Ezekiel', 'Dodimead', 'Bebb', '98-275-0946', 'ebebbu@whitehouse.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (32, 'Homerus', 'MacKnocker', 'Local', '77-583-0828', 'hlocalv@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (33, 'Alane', 'Losebie', 'Desorts', '79-164-1580', 'adesortsw@gravatar.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (34, 'Christiana', 'Jonk', 'Oddboy', '16-283-1223', 'coddboyx@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (35, 'Anselm', 'Weildish', null, '01-041-2075', 'agatehousey@stanford.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (36, 'Patsy', 'Antonias', 'Camillo', '35-234-6220', 'pcamilloz@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (37, 'Jeramie', 'Warwicker', null, '97-478-6979', 'jrobecon10@dedecms.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (38, 'Boy', 'Doldon', 'Pikett', '06-645-4542', 'bpikett11@github.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (39, 'Gaven', 'Yakubowicz', 'Redmond', '77-371-1135', 'gredmond12@smh.com.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (40, 'Lorant', 'Lindbergh', null, '64-849-4019', 'lnajafian13@g.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (41, 'Stacee', 'Burfitt', 'Downes', '12-496-0377', 'sdownes14@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (42, 'Vinnie', 'Verbeke', null, '75-912-1136', 'vbreitler15@thetimes.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (43, 'Briny', 'Dzenisenka', 'Brownrigg', '89-372-7296', 'bbrownrigg16@java.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (44, 'Marco', 'Stobbart', null, '09-001-3490', 'mcathrall17@bandcamp.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (45, 'Binky', 'Reubbens', 'Spender', '88-633-9632', 'bspender18@shareasale.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (46, 'Mariska', 'Coneau', 'Aleksandrev', '58-963-4807', 'maleksandrev19@zdnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (47, 'Leland', 'Trank', 'Hardin', '62-646-4290', 'lhardin1a@google.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (48, 'Jana', 'Conahy', 'O''Loughlin', '28-267-1091', 'joloughlin1b@google.es', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (49, 'Stesha', 'Brobyn', 'Sodeau', '27-157-9098', 'ssodeau1c@sphinn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (50, 'Stu', 'Scudder', 'Dinis', '42-581-3323', 'sdinis1d@last.fm', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (51, 'Kacie', 'Petel', 'Noakes', '54-376-3835', 'knoakes1e@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (52, 'Moll', 'Oxlade', null, '24-179-7379', 'mwhitecross1f@hp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (53, 'Belvia', 'Sergent', 'Duran', '64-108-6646', 'bduran1g@princeton.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (54, 'Andrew', 'Dunphie', 'Bissett', '66-658-6762', 'abissett1h@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (55, 'Sampson', 'Tatum', 'Statefield', '09-283-1288', 'sstatefield1i@columbia.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (56, 'Rocky', 'Sowthcote', 'Harvard', '15-021-3891', 'rharvard1j@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (57, 'Felicity', 'Jayme', 'Vreiberg', '93-085-8846', 'fvreiberg1k@quantcast.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (58, 'Jorry', 'Whetton', 'Deighton', '62-590-5592', 'jdeighton1l@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (59, 'Sonny', 'Birrell', null, '01-993-8583', 'swaadenburg1m@reuters.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (60, 'Susana', 'Ebben', 'Born', '94-653-3314', 'sborn1n@businesswire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (61, 'Lilian', 'Hails', 'Norres', '72-141-9959', 'lnorres1o@spiegel.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (62, 'Rachele', 'Priddy', 'Dugald', '92-834-0886', 'rdugald1p@seesaa.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (63, 'Junie', 'Peatt', 'Wycliffe', '09-914-3544', 'jwycliffe1q@abc.net.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (64, 'Laird', 'Oswell', 'Foxcroft', '36-952-6229', 'lfoxcroft1r@blogs.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (65, 'Jewell', 'Lantuff', 'Walkingshaw', '87-800-7112', 'jwalkingshaw1s@usda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (66, 'Jacenta', 'Benneyworth', 'Firmin', '76-526-2382', 'jfirmin1t@unblog.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (67, 'Talbot', 'Sullivan', 'Burtonshaw', '59-849-9938', 'tburtonshaw1u@xinhuanet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (68, 'Melvyn', 'Geraudy', null, '31-819-7185', 'mbrassington1v@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (69, 'Elton', 'Kings', 'Lapthorn', '67-112-3410', 'elapthorn1w@qq.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (70, 'Scarlet', 'Jouning', 'Allred', '71-061-7147', 'sallred1x@ucsd.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (71, 'Katya', 'Cluff', 'Nobles', '69-538-0372', 'knobles1y@macromedia.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (72, 'Joya', 'Potebury', 'Peddar', '62-116-3927', 'jpeddar1z@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (73, 'Darcy', 'Tysall', 'Kosiada', '78-897-1140', 'dkosiada20@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (74, 'Liz', 'Doone', 'Helbeck', '51-529-2775', 'lhelbeck21@google.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (75, 'Adriano', 'Curm', 'Tunmore', '53-336-9771', 'atunmore22@slideshare.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (76, 'Cornela', 'Alti', 'Bousquet', '14-703-6643', 'cbousquet23@delicious.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (77, 'Honor', 'Nassau', 'Lean', '03-997-5252', 'hlean24@tamu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (78, 'Row', 'Niezen', 'Innott', '70-935-1907', 'rinnott25@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (79, 'Ariel', 'Lentsch', 'Kingswood', '14-546-4988', 'akingswood26@google.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (80, 'Bennie', 'Blodgett', 'Yakobovitz', '22-662-1841', 'byakobovitz27@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (81, 'Rey', 'Thieme', null, '83-908-5800', 'rkield28@360.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (82, 'Faun', 'Brosini', null, '90-936-9219', 'fpenke29@jiathis.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (83, 'Minette', 'Frankema', 'Record', '70-785-5487', 'mrecord2a@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (84, 'Moishe', 'Fluger', 'Sedwick', '47-308-1662', 'msedwick2b@cnn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (85, 'Paige', 'Fazackerley', 'Tyer', '37-310-0932', 'ptyer2c@baidu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (86, 'Elia', 'Yellowlea', 'Somerbell', '86-114-9938', 'esomerbell2d@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (87, 'Arman', 'Orts', null, '68-336-7667', 'atunna2e@cargocollective.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (88, 'Genni', 'Leigh', null, '16-561-0380', 'gfantone2f@samsung.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (89, 'Josefa', 'Knightsbridge', 'Jepensen', '13-311-8190', 'jjepensen2g@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (90, 'Chrissie', 'Beseke', 'Giabuzzi', '07-890-8578', 'cgiabuzzi2h@xrea.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (91, 'Englebert', 'Tansey', 'Blagden', '97-252-4372', 'eblagden2i@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (92, 'Viviana', 'Ramel', 'Brockwell', '35-070-0339', 'vbrockwell2j@utexas.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (93, 'Remington', 'McAlinden', 'Quiney', '09-112-5226', 'rquiney2k@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (94, 'Frannie', 'Paviour', null, '95-095-0734', 'fnorster2l@stanford.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (95, 'Adda', 'Jakucewicz', 'Soot', '60-537-6231', 'asoot2m@naver.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (96, 'Leroi', 'Pyer', 'Cohrs', '07-813-5379', 'lcohrs2n@slate.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (97, 'Maxim', 'Morman', 'Malter', '96-821-0197', 'mmalter2o@usnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (98, 'Noel', 'Jenoure', null, '06-679-7067', 'nlampke2p@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (99, 'Derrik', 'Wilkenson', null, '11-119-2687', 'dlaval2q@noaa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (100, 'Chip', 'Stennings', 'Quoit', '82-552-0368', 'cquoit2r@telegraph.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (101, 'Marj', 'Spaule', 'Thorrold', '09-017-6199', 'mthorrold2s@domainmarket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (102, 'Petronilla', 'Bras', 'Drogan', '42-255-0513', 'pdrogan2t@tamu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (103, 'Yale', 'Vodden', 'Buxcy', '45-847-7372', 'ybuxcy2u@skype.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (104, 'Orelee', 'Guyet', 'Daddow', '36-315-7587', 'odaddow2v@paypal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (105, 'Joshuah', 'Nitti', 'Pelling', '47-513-3440', 'jpelling2w@purevolume.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (106, 'Shoshanna', 'Bentame', 'Press', '74-813-6918', 'spress2x@dailymail.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (107, 'Bette', 'Russel', 'Champken', '91-851-5073', 'bchampken2y@google.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (108, 'Daphne', 'Dobbyn', null, '74-263-3676', 'dgabala2z@globo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (109, 'Caty', 'Sudlow', null, '48-785-3738', 'cmcentegart30@pen.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (110, 'Amy', 'Otley', 'Fearnyough', '86-221-0487', 'afearnyough31@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (111, 'Conny', 'Urpeth', 'Miranda', '43-468-1126', 'cmiranda32@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (112, 'Kore', 'Getch', 'Giurio', '02-554-9560', 'kgiurio33@discovery.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (113, 'Fleur', 'Sutlieff', null, '04-777-0254', 'fenzley34@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (114, 'Eden', 'Barnewille', 'Burrill', '51-931-3532', 'eburrill35@bloglovin.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (115, 'Melva', 'Frowd', 'de Zamora', '31-018-0170', 'mdezamora36@mail.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (116, 'Rollin', 'Foat', 'Beausang', '54-781-6465', 'rbeausang37@mapy.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (117, 'Cirilo', 'Cheel', 'Marshland', '86-170-2694', 'cmarshland38@sun.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (118, 'Ced', 'Copner', 'Swadling', '23-430-7576', 'cswadling39@mayoclinic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (119, 'Bethina', 'Badrick', 'Coye', '18-042-5715', 'bcoye3a@ibm.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (120, 'Cass', 'Turbern', 'Bulch', '01-531-1875', 'cbulch3b@ed.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (121, 'Noah', 'Sickamore', 'Pollendine', '11-686-6230', 'npollendine3c@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (122, 'Oralla', 'Sipson', 'Westhead', '13-445-7050', 'owesthead3d@hibu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (123, 'Neille', 'Iddons', 'Broadwood', '50-239-7415', 'nbroadwood3e@businessweek.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (124, 'Ardenia', 'Loisi', null, '15-036-0924', 'apeplaw3f@geocities.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (125, 'Coletta', 'Kob', 'Adanet', '60-430-1426', 'cadanet3g@accuweather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (126, 'Rosalynd', 'Andrea', null, '71-525-8027', 'rkettley3h@cbslocal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (127, 'Modestine', 'Dunkerly', 'Chasmor', '68-381-4123', 'mchasmor3i@123-reg.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (128, 'Evelyn', 'Clousley', 'Rodnight', '83-148-9466', 'erodnight3j@nyu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (129, 'Ernesto', 'Halsho', 'Sudell', '46-729-6772', 'esudell3k@upenn.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (130, 'Vin', 'Birk', 'Calder', '37-327-4943', 'vcalder3l@redcross.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (131, 'Kristin', 'Burgoine', null, '40-624-1287', 'kmorrice3m@princeton.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (132, 'Hall', 'Brouard', 'Gennerich', '21-829-1103', 'hgennerich3n@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (133, 'Velvet', 'Eitter', 'Phorsby', '66-971-1990', 'vphorsby3o@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (134, 'Enrico', 'Philot', 'Spering', '92-484-9248', 'espering3p@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (135, 'Bartolomeo', 'Jursch', 'Lisett', '45-380-7342', 'blisett3q@google.nl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (136, 'Dareen', 'Aldrin', null, '59-335-0133', 'dreaditt3r@gov.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (137, 'Averil', 'Burges', 'Plett', '05-191-0155', 'aplett3s@house.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (138, 'Clotilda', 'Hiddy', 'Pinwell', '87-032-3445', 'cpinwell3t@army.mil', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (139, 'Pasquale', 'Hub', 'Raddenbury', '27-797-9758', 'praddenbury3u@istockphoto.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (140, 'Trixi', 'Fontin', 'McCroary', '47-388-1735', 'tmccroary3v@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (141, 'Thomasa', 'Eich', null, '41-042-5484', 'tgraffin3w@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (142, 'Odie', 'Crebbin', 'Grinston', '61-024-5016', 'ogrinston3x@who.int', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (143, 'Alyda', 'Tregiddo', 'Petrovic', '56-310-1130', 'apetrovic3y@rambler.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (144, 'Shelton', 'Chuney', 'Purrington', '63-665-6960', 'spurrington3z@paypal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (145, 'Fax', 'Shawcroft', 'Seabert', '24-511-7664', 'fseabert40@xinhuanet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (146, 'Allianora', 'Leitche', 'Sired', '51-491-3790', 'asired41@squarespace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (147, 'Tedd', 'Oscroft', 'Roalfe', '09-309-2082', 'troalfe42@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (148, 'Candie', 'Mingard', 'Colerick', '13-674-6807', 'ccolerick43@bloomberg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (149, 'Lowrance', 'Smither', 'Piggen', '40-401-5870', 'lpiggen44@globo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (150, 'Sig', 'Thunderchief', 'Castree', '05-135-5347', 'scastree45@mtv.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (151, 'Merci', 'Beszant', 'McLevie', '17-599-7802', 'mmclevie46@odnoklassniki.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (152, 'Killy', 'Fasset', 'Bigrigg', '94-185-3817', 'kbigrigg47@zimbio.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (153, 'Caesar', 'Upton', 'Trace', '50-198-5437', 'ctrace48@usa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (154, 'Mariette', 'Gutowska', 'Vinden', '57-051-4436', 'mvinden49@pagesperso-orange.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (155, 'Cynde', 'Hatchette', 'Kerwood', '27-856-1571', 'ckerwood4a@chronoengine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (156, 'Bondon', 'Benck', null, '78-323-3586', 'bblevin4b@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (157, 'Innis', 'Mallett', null, '16-096-3585', 'icarous4c@cargocollective.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (158, 'Brynna', 'Jouanot', 'Pettko', '49-236-5276', 'bpettko4d@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (159, 'Art', 'Wegner', null, '67-666-5688', 'ablakeborough4e@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (160, 'Donnie', 'Jaggli', null, '77-411-7875', 'dverryan4f@unicef.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (161, 'Nial', 'McAndie', 'Cotterell', '84-386-2264', 'ncotterell4g@fema.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (162, 'Hurleigh', 'Casswell', null, '01-297-9467', 'htejero4h@paypal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (163, 'Guendolen', 'Slipper', 'Verdun', '05-694-8831', 'gverdun4i@newyorker.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (164, 'Zechariah', 'Madgewick', 'Baudassi', '38-611-0105', 'zbaudassi4j@redcross.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (165, 'Lenette', 'MacDearmont', 'Piscot', '58-829-8373', 'lpiscot4k@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (166, 'Janelle', 'Anker', 'Ellor', '54-200-2925', 'jellor4l@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (167, 'Melvin', 'Posner', 'Shalliker', '96-399-1658', 'mshalliker4m@diigo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (168, 'Panchito', 'Lerego', null, '87-983-1877', 'pfomichkin4n@economist.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (169, 'Banky', 'Akester', null, '48-382-1483', 'bcorsor4o@wix.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (170, 'Erwin', 'Follin', 'Gallihaulk', '32-028-3425', 'egallihaulk4p@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (171, 'Clevey', 'Corston', 'Brunelleschi', '39-568-3385', 'cbrunelleschi4q@netscape.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (172, 'Trefor', 'Bangs', null, '18-138-3339', 'twillis4r@mail.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (173, 'Peri', 'Sporner', 'Cholwell', '02-948-1147', 'pcholwell4s@businessinsider.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (174, 'Phylys', 'Kitchenside', null, '47-035-8678', 'pspillane4t@utexas.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (175, 'Vickie', 'Mariot', 'Cariss', '92-710-6773', 'vcariss4u@w3.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (176, 'Lottie', 'Garton', 'Habbijam', '85-081-0918', 'lhabbijam4v@timesonline.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (177, 'Filip', 'Arlt', 'Marzele', '27-220-3334', 'fmarzele4w@scribd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (178, 'Hortense', 'Sisland', 'Shapland', '46-110-3234', 'hshapland4x@mozilla.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (179, 'Mordecai', 'Clayborn', 'Hindmore', '70-317-2338', 'mhindmore4y@weather.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (180, 'Heinrik', 'Wakeford', null, '59-384-9351', 'hnolton4z@acquirethisname.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (181, 'Beverlie', 'Droogan', 'McKimmie', '76-838-2299', 'bmckimmie50@rediff.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (182, 'Gherardo', 'Kenningham', 'Leguay', '35-463-4676', 'gleguay51@1und1.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (183, 'Brocky', 'Coch', 'Enser', '13-823-4654', 'benser52@cocolog-nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (184, 'Earvin', 'Boydle', null, '71-952-7399', 'ehamill53@purevolume.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (185, 'Lynn', 'Pagden', 'Acres', '03-537-4780', 'lacres54@merriam-webster.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (186, 'Carmina', 'Ludovico', 'Le feuvre', '45-465-4645', 'clefeuvre55@github.io', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (187, 'Maurice', 'Sodory', 'Gisburn', '50-115-8879', 'mgisburn56@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (188, 'Bonni', 'Sloane', 'Seeking', '26-394-7460', 'bseeking57@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (189, 'Fransisco', 'Bromehed', null, '36-740-8023', 'fstedell58@who.int', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (190, 'Gabie', 'Musslewhite', 'Ollerton', '60-553-5457', 'gollerton59@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (191, 'Gunner', 'O''Luby', 'Somerton', '78-680-2217', 'gsomerton5a@cocolog-nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (192, 'Wynny', 'Menham', null, '32-180-1587', 'wcoggins5b@biglobe.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (193, 'Tomaso', 'Champain', 'Bannard', '34-060-0769', 'tbannard5c@godaddy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (194, 'Sidonia', 'Gainsbury', 'Dubery', '81-241-2669', 'sdubery5d@hugedomains.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (195, 'Silvana', 'Goodwell', 'Cormode', '27-701-5007', 'scormode5e@goodreads.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (196, 'Janaye', 'Wimbridge', 'Barchrameev', '38-606-3690', 'jbarchrameev5f@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (197, 'Juliane', 'Kiessel', 'Nenci', '12-246-2815', 'jnenci5g@sfgate.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (198, 'Dominick', 'Wakelam', null, '07-804-3082', 'dfosdyke5h@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (199, 'Garwin', 'Eveling', 'Monaghan', '10-694-9810', 'gmonaghan5i@cnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (200, 'Leodora', 'Rummery', null, '67-691-2951', 'lconyard5j@flavors.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (201, 'Sergei', 'Govinlock', 'Sket', '99-924-5015', 'ssket5k@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (202, 'Roselin', 'Ashdown', 'Josse', '40-214-1169', 'rjosse5l@ameblo.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (203, 'Durward', 'Hulcoop', null, '05-575-0773', 'dnickoles5m@qq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (204, 'Kin', 'Brightie', null, '16-644-7527', 'koller5n@apache.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (205, 'Torrie', 'Galvin', 'Gerrey', '21-967-1874', 'tgerrey5o@privacy.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (206, 'Sidnee', 'Farnon', 'Folliott', '20-985-5810', 'sfolliott5p@sourceforge.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (207, 'Neron', 'Cornell', 'Yantsev', '58-169-7446', 'nyantsev5q@reference.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (208, 'Cazzie', 'Ladbrooke', 'Baxstair', '36-568-4818', 'cbaxstair5r@thetimes.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (209, 'Isidoro', 'Youd', null, '88-126-4723', 'imertel5s@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (210, 'Tadio', 'Shemilt', null, '73-198-7787', 'tkite5t@bandcamp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (211, 'Carlo', 'Boneham', 'Kenen', '55-991-6190', 'ckenen5u@theatlantic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (212, 'Donnell', 'Burree', 'Slayford', '20-280-8060', 'dslayford5v@plala.or.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (213, 'Eugenius', 'Caughan', 'Heaker', '65-216-4620', 'eheaker5w@last.fm', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (214, 'Werner', 'Allcott', null, '35-016-3672', 'wcambridge5x@ning.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (215, 'Nancee', 'Thalmann', 'Mashro', '94-108-8861', 'nmashro5y@comcast.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (216, 'Theobald', 'Zuann', 'Annon', '39-060-9142', 'tannon5z@wordpress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (217, 'Jeana', 'Arnely', 'Golthorpp', '77-294-8547', 'jgolthorpp60@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (218, 'Deina', 'Chesters', 'Tummons', '07-303-4450', 'dtummons61@tamu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (219, 'Phillis', 'Terrelly', null, '47-491-5208', 'pjanaszkiewicz62@pbs.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (220, 'Elianora', 'Quantrell', 'Dudliston', '07-283-5190', 'edudliston63@dailymotion.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (221, 'Gerardo', 'Hatherell', null, '39-819-1993', 'gvanarsdale64@blogspot.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (222, 'Ainsley', 'Greetham', 'Shearme', '31-581-9573', 'ashearme65@engadget.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (223, 'Barnabe', 'Dunridge', 'Treacher', '00-897-0288', 'btreacher66@scientificamerican.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (224, 'Benetta', 'Hackelton', 'Samter', '55-133-9707', 'bsamter67@goo.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (225, 'Mattie', 'Shenley', 'Deveraux', '12-429-2098', 'mdeveraux68@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (226, 'Fannie', 'Mantz', 'Bardnam', '22-652-5854', 'fbardnam69@nbcnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (227, 'Mathian', 'Dixcey', null, '26-740-6842', 'mmerton6a@un.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (228, 'Neal', 'Schruur', 'Maulden', '46-493-2497', 'nmaulden6b@merriam-webster.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (229, 'Nevile', 'Hatchette', 'Gerssam', '89-296-4321', 'ngerssam6c@yellowbook.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (230, 'Janet', 'Skellion', 'Drinkeld', '58-531-8885', 'jdrinkeld6d@discuz.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (231, 'Gunter', 'McNickle', 'Core', '71-828-4115', 'gcore6e@plala.or.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (232, 'Wildon', 'Kidston', 'Groll', '75-332-9662', 'wgroll6f@discovery.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (233, 'Ulberto', 'Haymes', 'Bowell', '40-872-4899', 'ubowell6g@quantcast.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (234, 'Hedy', 'Stoker', 'Sperling', '65-486-8807', 'hsperling6h@goodreads.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (235, 'Fredi', 'Yacobsohn', 'Abramson', '71-519-4014', 'fabramson6i@wsj.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (236, 'Novelia', 'Saintsbury', 'Skillings', '13-168-7711', 'nskillings6j@sbwire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (237, 'Turner', 'Bartczak', 'Mollett', '10-006-7979', 'tmollett6k@globo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (238, 'Alyss', 'Wedmore', 'Morphey', '71-832-0239', 'amorphey6l@fastcompany.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (239, 'Wilden', 'Smithson', 'Poter', '74-972-1315', 'wpoter6m@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (240, 'Tory', 'Debney', 'Polding', '93-159-6617', 'tpolding6n@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (241, 'Nataniel', 'Abbison', 'Marcinkus', '73-612-0276', 'nmarcinkus6o@webeden.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (242, 'Andre', 'Fredson', 'Stancliffe', '92-561-2280', 'astancliffe6p@tripadvisor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (243, 'Carrol', 'Armal', null, '38-062-4917', 'cfillgate6q@telegraph.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (244, 'Minerva', 'Daft', 'Pragnall', '42-905-0308', 'mpragnall6r@census.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (245, 'Leona', 'Bowers', null, '93-814-4539', 'ldommersen6s@tumblr.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (246, 'Gregorio', 'Agiolfinger', 'Zavattari', '78-277-3417', 'gzavattari6t@intel.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (247, 'Anselma', 'Le Brom', 'Dreossi', '26-545-1124', 'adreossi6u@goo.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (248, 'Gabie', 'Noades', 'Karlowicz', '30-649-3573', 'gkarlowicz6v@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (249, 'Cully', 'Screaton', 'Lennarde', '63-340-2373', 'clennarde6w@pen.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (250, 'Danie', 'Attride', 'Thirlaway', '88-590-4084', 'dthirlaway6x@sitemeter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (251, 'Sterne', 'Kuban', 'De Vuyst', '93-100-6770', 'sdevuyst6y@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (252, 'Ken', 'Edie', 'Worsfold', '95-039-5637', 'kworsfold6z@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (253, 'Lida', 'Weare', 'Freebury', '43-938-8352', 'lfreebury70@blogspot.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (254, 'Eolande', 'Stubbin', 'Eglaise', '50-023-8712', 'eeglaise71@sourceforge.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (255, 'Francklin', 'Broomer', 'Smithson', '08-626-7567', 'fsmithson72@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (256, 'Jacquelin', 'Fend', 'Czajkowski', '08-278-0910', 'jczajkowski73@tiny.cc', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (257, 'Mischa', 'Rule', 'Wenham', '93-757-0030', 'mwenham74@trellian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (258, 'Wandis', 'Von Welden', 'Visco', '15-005-1957', 'wvisco75@census.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (259, 'Ynes', 'Brockie', 'Philippon', '17-852-7942', 'yphilippon76@google.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (260, 'Ruthie', 'Bovingdon', 'Bazoge', '43-904-9601', 'rbazoge77@theglobeandmail.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (261, 'Errol', 'Larkcum', 'Hamson', '26-417-5795', 'ehamson78@japanpost.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (262, 'Adelaide', 'Corss', null, '91-536-4419', 'aerett79@wsj.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (263, 'Krisha', 'Stockin', 'Bridgestock', '67-996-1377', 'kbridgestock7a@nhs.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (264, 'Onfre', 'Fortnon', 'Shotter', '95-828-1860', 'oshotter7b@chronoengine.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (265, 'Rollin', 'Espinoy', 'Peattie', '90-367-2624', 'rpeattie7c@163.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (266, 'Krishna', 'Tombleson', 'Heinsen', '85-106-3699', 'kheinsen7d@marriott.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (267, 'Jermaine', 'Hills', 'Harme', '76-890-7605', 'jharme7e@diigo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (268, 'Jerrold', 'Bridson', 'Uebel', '05-551-2769', 'juebel7f@xing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (269, 'Rock', 'Stoffersen', 'Iban', '08-236-6727', 'riban7g@hibu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (270, 'Betta', 'Jaqueminet', 'Sackur', '54-858-7683', 'bsackur7h@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (271, 'Mahmud', 'Pollett', 'Valois', '14-429-3238', 'mvalois7i@stumbleupon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (272, 'Angus', 'Edmeades', 'Creeboe', '48-434-0363', 'acreeboe7j@seesaa.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (273, 'Cristina', 'Spowart', 'Dimmne', '85-476-2361', 'cdimmne7k@creativecommons.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (274, 'Evangelina', 'Chaplain', null, '34-027-6370', 'egyde7l@google.co.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (275, 'Lauryn', 'Jollands', null, '29-744-7186', 'lfuzzens7m@free.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (276, 'Ophelia', 'Brunker', null, '91-624-6440', 'oamoss7n@va.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (277, 'Klaus', 'Kettow', 'Claricoates', '82-685-6349', 'kclaricoates7o@tinypic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (278, 'Prince', 'Brandts', 'Sherville', '99-627-9306', 'psherville7p@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (279, 'Valentia', 'Tebbe', 'McCathy', '54-675-7858', 'vmccathy7q@sciencedirect.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (280, 'Jacky', 'Dingwall', 'Stork', '75-452-1794', 'jstork7r@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (281, 'Josh', 'Gilliland', 'Navarro', '55-329-7738', 'jnavarro7s@meetup.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (282, 'Allard', 'Scipsey', null, '53-323-2304', 'atansley7t@purevolume.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (283, 'Lizette', 'Bolt', 'Toby', '90-407-3607', 'ltoby7u@netscape.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (284, 'Helge', 'Elies', 'Michie', '20-042-4161', 'hmichie7v@smugmug.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (285, 'Brander', 'Veness', 'Cansdell', '35-680-4546', 'bcansdell7w@chron.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (286, 'Cheslie', 'Huntall', 'Briiginshaw', '23-492-2148', 'cbriiginshaw7x@dropbox.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (287, 'Dorice', 'Rewcassell', 'Bliven', '83-975-8467', 'dbliven7y@tamu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (288, 'Franchot', 'Strodder', 'Godwin', '81-435-4802', 'fgodwin7z@woothemes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (289, 'Irita', 'Manthorpe', 'Le Marquand', '54-837-9679', 'ilemarquand80@phpbb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (290, 'Shoshana', 'Greensitt', null, '83-995-7398', 'spaulillo81@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (291, 'Baillie', 'Marsters', 'Corriea', '14-749-5905', 'bcorriea82@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (292, 'Basilio', 'Dolbey', 'Spong', '47-909-7799', 'bspong83@pbs.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (293, 'Alfi', 'Gaskoin', 'Gallager', '72-598-6066', 'agallager84@odnoklassniki.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (294, 'Bealle', 'Tracy', 'Kirton', '66-887-3140', 'bkirton85@issuu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (295, 'West', 'Mantrup', 'McGillicuddy', '77-910-8073', 'wmcgillicuddy86@patch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (296, 'Eudora', 'Brunke', 'Enston', '50-993-8876', 'eenston87@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (297, 'Rogers', 'Bedward', 'Geram', '26-912-4283', 'rgeram88@ask.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (298, 'Paige', 'Casazza', 'Valentetti', '57-146-5037', 'pvalentetti89@purevolume.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (299, 'Patrizius', 'Drinnan', 'Jeannot', '87-330-3380', 'pjeannot8a@deviantart.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (300, 'Chloris', 'Duesbury', 'Genever', '35-983-9291', 'cgenever8b@squidoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (301, 'Candra', 'Iltchev', 'Minet', '22-909-8625', 'cminet8c@buzzfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (302, 'Guilbert', 'Bullus', 'McDonnell', '98-055-6946', 'gmcdonnell8d@prweb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (303, 'Cobb', 'Strother', 'Donisi', '47-010-2696', 'cdonisi8e@dmoz.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (304, 'Waldo', 'Redholes', 'Rattenberie', '17-091-6615', 'wrattenberie8f@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (305, 'Muhammad', 'Caldayrou', 'Rembaud', '15-987-0025', 'mrembaud8g@prlog.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (306, 'Brittan', 'Orteau', null, '60-030-8219', 'bgoodhall8h@cdbaby.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (307, 'Nichole', 'Mabbitt', 'Bingall', '97-891-8255', 'nbingall8i@mayoclinic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (308, 'Fredra', 'Behan', 'Symcoxe', '03-431-5883', 'fsymcoxe8j@arizona.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (309, 'Edsel', 'Meale', 'Grundy', '01-101-5588', 'egrundy8k@tuttocitta.it', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (310, 'Kincaid', 'Wadsworth', 'Jerome', '62-137-0117', 'kjerome8l@vkontakte.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (311, 'Sholom', 'Coulman', 'Cowles', '16-770-2400', 'scowles8m@skype.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (312, 'Dominic', 'Garvagh', 'Brayn', '53-301-7341', 'dbrayn8n@google.com.hk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (313, 'Art', 'Vakhlov', null, '65-714-8554', 'aedleston8o@discuz.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (314, 'Bennie', 'Kyberd', 'Fullalove', '09-483-0264', 'bfullalove8p@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (315, 'Gloriana', 'Bawden', null, '90-669-6645', 'gpammenter8q@zimbio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (316, 'Land', 'Blackden', 'Giddings', '45-462-6332', 'lgiddings8r@si.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (317, 'Zak', 'Pietron', 'Thing', '36-176-5036', 'zthing8s@domainmarket.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (318, 'Juliana', 'Tomalin', null, '09-303-3794', 'jmullen8t@reference.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (319, 'Niki', 'Piscopiello', 'Meco', '92-554-1325', 'nmeco8u@rediff.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (320, 'Quintana', 'Pashan', 'Rouby', '52-919-9600', 'qrouby8v@cdc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (321, 'Hansiain', 'Greenhall', 'Buckerfield', '87-904-4205', 'hbuckerfield8w@fc2.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (322, 'Ariela', 'Sonnenschein', 'Netherwood', '42-852-8849', 'anetherwood8x@ning.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (323, 'Emmet', 'Proudlove', 'Allden', '62-610-8104', 'eallden8y@freewebs.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (324, 'Suzann', 'O''Sherin', 'Rittelmeyer', '17-338-8176', 'srittelmeyer8z@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (325, 'Eberhard', 'Meeking', 'Millions', '13-833-9651', 'emillions90@google.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (326, 'Denni', 'Cooch', 'Pinkney', '21-582-9453', 'dpinkney91@usgs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (327, 'Courtenay', 'Handover', 'Wyd', '99-679-7016', 'cwyd92@mayoclinic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (328, 'Ladonna', 'Brookson', 'Trewartha', '01-377-0970', 'ltrewartha93@japanpost.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (329, 'Gianna', 'O''Fallon', 'Denkel', '27-873-5666', 'gdenkel94@digg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (330, 'Dionne', 'Sorensen', null, '51-090-7073', 'dpinder95@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (331, 'Trudie', 'Bolan', 'Scrivin', '20-035-8033', 'tscrivin96@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (332, 'Saunderson', 'Hackworthy', 'Sapir', '31-617-5699', 'ssapir97@comcast.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (333, 'Lucita', 'Lockney', 'Bullus', '93-605-6257', 'lbullus98@digg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (334, 'Susannah', 'Goalley', 'Peerman', '38-642-5597', 'speerman99@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (335, 'Haley', 'Millery', 'Mansfield', '41-062-8609', 'hmansfield9a@simplemachines.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (336, 'Isaak', 'Blaker', 'Guerre', '14-635-8374', 'iguerre9b@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (337, 'Ulrike', 'Mival', null, '95-225-2313', 'uwey9c@sitemeter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (338, 'Sheilakathryn', 'Alentyev', 'Gitsham', '89-689-5139', 'sgitsham9d@ycombinator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (339, 'Lay', 'Lucken', null, '77-226-3392', 'lmalloch9e@trellian.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (340, 'Lana', 'Cocozza', 'Gaize', '73-961-2572', 'lgaize9f@wikia.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (341, 'Libbi', 'Wickham', 'Woffinden', '78-436-1490', 'lwoffinden9g@yolasite.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (342, 'Jeanne', 'Maps', 'Litzmann', '35-030-8730', 'jlitzmann9h@disqus.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (343, 'Cyndie', 'Dalziel', 'Schimmang', '23-386-7107', 'cschimmang9i@chronoengine.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (344, 'Jaquelin', 'Bourthouloume', 'Pickard', '68-514-7788', 'jpickard9j@bbc.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (345, 'Clea', 'Biggen', 'Lindenfeld', '47-748-7519', 'clindenfeld9k@skyrock.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (346, 'Bennie', 'Cayton', 'Kattenhorn', '73-107-8216', 'bkattenhorn9l@wikia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (347, 'Cyndie', 'Joynson', 'Moxstead', '70-046-2374', 'cmoxstead9m@eepurl.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (348, 'Cordula', 'Sterricks', 'Pitson', '92-508-4697', 'cpitson9n@histats.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (349, 'Annabel', 'Ridsdale', 'Brommage', '26-589-2411', 'abrommage9o@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (350, 'Karyn', 'Vasilyev', 'Nazareth', '46-846-2465', 'knazareth9p@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (351, 'Timmi', 'Heale', 'Obington', '97-838-4693', 'tobington9q@drupal.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (352, 'Glynnis', 'Gouly', 'Dalziel', '47-653-2980', 'gdalziel9r@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (353, 'Jamie', 'Beard', 'Briers', '70-616-6538', 'jbriers9s@tripod.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (354, 'Roze', 'Annesley', 'Blamey', '57-542-6736', 'rblamey9t@washingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (355, 'Dalila', 'Bembridge', 'Phalip', '99-467-1689', 'dphalip9u@ucla.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (356, 'Jase', 'Labbati', 'Zisneros', '51-332-3802', 'jzisneros9v@altervista.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (357, 'Mattias', 'Raynes', 'Pawlyn', '92-274-9480', 'mpawlyn9w@ed.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (358, 'Skippie', 'Illidge', null, '51-928-1001', 'srosenblad9x@qq.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (359, 'Elsworth', 'Barltrop', 'Martygin', '41-808-7180', 'emartygin9y@e-recht24.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (360, 'Artus', 'Hadwen', 'Arkow', '82-336-7588', 'aarkow9z@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (361, 'Jehu', 'Gerretsen', 'Scolts', '12-945-9724', 'jscoltsa0@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (362, 'Kelci', 'Boig', 'Nestor', '30-278-6255', 'knestora1@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (363, 'Ruthie', 'Wolfindale', 'Pariss', '09-548-2302', 'rparissa2@hugedomains.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (364, 'Felike', 'Plomer', 'McGinty', '30-501-1339', 'fmcgintya3@photobucket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (365, 'Tarra', 'Farncombe', 'Banks', '16-395-7455', 'tbanksa4@friendfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (366, 'Blancha', 'Steanson', 'Heliar', '38-029-9819', 'bheliara5@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (367, 'Noe', 'Dopson', 'Birks', '65-405-4406', 'nbirksa6@rediff.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (368, 'Claudell', 'Wedderburn', null, '49-329-7090', 'cblenkensopa7@php.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (369, 'Sileas', 'Grigorescu', 'Snowdon', '49-014-4612', 'ssnowdona8@deviantart.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (370, 'Nicolas', 'Serchwell', 'Dowe', '72-026-8259', 'ndowea9@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (371, 'Genevieve', 'Kline', 'Cready', '97-620-3362', 'gcreadyaa@scribd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (372, 'Rozella', 'Nicolson', 'Carrack', '43-388-6715', 'rcarrackab@bizjournals.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (373, 'Edin', 'Biesty', null, '31-867-7052', 'eolcotac@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (374, 'Marilyn', 'Catherine', null, '19-413-0859', 'mcrightonad@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (375, 'Jacob', 'Crang', 'Tailour', '92-455-3831', 'jtailourae@oracle.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (376, 'Freda', 'Emanuelov', 'Nice', '58-284-9633', 'fniceaf@e-recht24.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (377, 'Onfre', 'Josephsen', null, '67-828-7633', 'ostoneleyag@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (378, 'Kelsey', 'Gotliffe', 'McKeurton', '59-226-8343', 'kmckeurtonah@webmd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (379, 'Marice', 'Bourdon', 'Sommersett', '73-900-3546', 'msommersettai@google.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (380, 'Jilleen', 'Chicchelli', 'Haucke', '00-596-2425', 'jhauckeaj@gmpg.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (381, 'Corrinne', 'Rossbrooke', 'Jagger', '50-334-7255', 'cjaggerak@patch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (382, 'Stearne', 'Segge', 'Ceschini', '83-737-5444', 'sceschinial@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (383, 'Torey', 'Blincow', null, '41-948-3256', 'twytheam@telegraph.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (384, 'Barnett', 'Rulton', 'Todhunter', '77-073-1982', 'btodhunteran@tamu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (385, 'Desmond', 'Bosomworth', 'Deekes', '26-142-5942', 'ddeekesao@mac.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (386, 'Dulcinea', 'Dyball', 'Dursley', '33-171-9581', 'ddursleyap@last.fm', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (387, 'Renie', 'Brandel', null, '63-824-4599', 'rwimpennyaq@ameblo.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (388, 'Mort', 'Laughnan', 'Courage', '15-931-0762', 'mcouragear@china.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (389, 'Darline', 'Woolfitt', 'Cattel', '58-377-3678', 'dcattelas@hostgator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (390, 'Sadye', 'McCome', 'Warrick', '11-040-8059', 'swarrickat@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (391, 'Cherish', 'Rizzillo', 'Readshaw', '28-916-5501', 'creadshawau@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (392, 'Rafaelita', 'Boatwright', 'Osbiston', '13-119-1723', 'rosbistonav@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (393, 'Marten', 'Saipy', 'Coleshill', '81-197-1273', 'mcoleshillaw@storify.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (394, 'Babita', 'Anscott', 'Ahrendsen', '01-042-7582', 'bahrendsenax@nationalgeographic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (395, 'Nahum', 'Brosch', 'Wellstead', '00-721-4309', 'nwellsteaday@google.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (396, 'Gottfried', 'Wisdom', 'Greste', '00-226-8009', 'ggresteaz@hubpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (397, 'Paulette', 'Hendron', 'Pardy', '65-301-3050', 'ppardyb0@facebook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (398, 'Gerladina', 'Losselyong', null, '67-075-6579', 'gnaptonb1@cnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (399, 'Brit', 'Jandl', null, '18-989-2740', 'bphippinb2@fda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (400, 'Karena', 'Ogelbe', null, '55-468-5513', 'kcoppensb3@cbsnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (401, 'Bourke', 'Hallgath', 'Espadero', '75-448-5274', 'bespaderob4@omniture.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (402, 'Rene', 'Putterill', null, '06-702-2391', 'rheersmab5@bloglines.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (403, 'Holly-anne', 'Sorrel', 'Braybrook', '87-150-5870', 'hbraybrookb6@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (404, 'Helen', 'Osborn', 'Tichelaar', '95-237-7004', 'htichelaarb7@google.com.hk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (405, 'Anya', 'Dentith', null, '70-778-2718', 'ascoldingb8@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (406, 'Sarina', 'Hanhart', 'Adicot', '23-641-5164', 'sadicotb9@fotki.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (407, 'Seth', 'Brown', null, '42-381-6920', 'ssirrba@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (408, 'Neala', 'Kolakowski', 'McCraine', '73-889-6265', 'nmccrainebb@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (409, 'Torey', 'Cribbott', 'Riguard', '85-054-7347', 'triguardbc@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (410, 'Dotti', 'Shortt', 'Ewin', '60-756-0284', 'dewinbd@list-manage.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (411, 'Kelcie', 'Sarvar', 'Goodhew', '51-079-0436', 'kgoodhewbe@mozilla.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (412, 'Marni', 'Dominico', null, '17-323-1922', 'msoanebf@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (413, 'Fayina', 'Goodred', 'Forsythe', '11-563-7610', 'fforsythebg@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (414, 'Rodolfo', 'Jagielski', 'Moult', '60-392-6067', 'rmoultbh@samsung.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (415, 'Clevie', 'Southam', 'Wimmer', '40-149-1563', 'cwimmerbi@marriott.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (416, 'Joan', 'Chastelain', 'Denington', '94-714-2939', 'jdeningtonbj@weather.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (417, 'Janice', 'Brecken', 'Dacres', '58-381-4724', 'jdacresbk@indiatimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (418, 'Arlana', 'Whyke', 'Reasun', '44-289-0148', 'areasunbl@hud.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (419, 'Gianni', 'Joskovitch', null, '12-354-4883', 'golechbm@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (420, 'Orella', 'Wasylkiewicz', 'Philipet', '60-927-4514', 'ophilipetbn@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (421, 'Pet', 'Buttwell', 'Bech', '00-207-7065', 'pbechbo@ucoz.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (422, 'Tedi', 'Tournie', 'Robez', '18-997-2937', 'trobezbp@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (423, 'Leticia', 'Quixley', 'Loddy', '40-673-2795', 'lloddybq@mlb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (424, 'Bevin', 'Fridlington', null, '15-905-7894', 'bscammellbr@ed.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (425, 'Ber', 'Willmore', 'Reuble', '27-749-0011', 'breublebs@miibeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (426, 'Bellanca', 'Sieur', 'Baroux', '34-664-3396', 'bbarouxbt@mlb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (427, 'Chickie', 'Maciejewski', 'Motton', '37-588-0982', 'cmottonbu@wisc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (428, 'Garrick', 'Bennoe', 'Kiebes', '29-986-0250', 'gkiebesbv@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (429, 'Paolo', 'Panniers', 'Asp', '60-925-2588', 'paspbw@blogspot.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (430, 'Gunter', 'Rustich', 'Braddick', '19-005-1777', 'gbraddickbx@comcast.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (431, 'Evin', 'Curner', 'Gerardeaux', '09-277-2087', 'egerardeauxby@patch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (432, 'Wallas', 'Skough', 'Schubuser', '08-580-2877', 'wschubuserbz@shinystat.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (433, 'Caron', 'Lancaster', 'Yude', '40-272-8420', 'cyudec0@digg.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (434, 'Marnie', 'Denerley', 'Hurtado', '98-270-5796', 'mhurtadoc1@google.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (435, 'Sky', 'Romaines', 'Kirsch', '85-929-0861', 'skirschc2@marriott.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (436, 'Phaedra', 'Gifford', null, '00-725-9930', 'psummersc3@friendfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (437, 'Ryley', 'Huguet', 'Ayris', '34-879-3890', 'rayrisc4@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (438, 'Tanhya', 'Dives', 'Mateos', '00-269-5821', 'tmateosc5@amazon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (439, 'Egbert', 'Dive', 'Penniall', '51-036-0385', 'epenniallc6@irs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (440, 'Deonne', 'Straniero', 'Gierhard', '33-424-0377', 'dgierhardc7@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (441, 'Doti', 'Leyzell', 'Ziems', '58-062-2189', 'dziemsc8@parallels.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (442, 'Valida', 'Codd', null, '90-664-1658', 'vlucianc9@twitter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (443, 'Rosalinda', 'Mears', 'Riddiough', '93-692-1045', 'rriddioughca@prnewswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (444, 'Willow', 'Valerio', 'Thomen', '91-011-3168', 'wthomencb@rambler.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (445, 'Florida', 'Knowlton', 'Cater', '95-310-6164', 'fcatercc@furl.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (446, 'Christophorus', 'Hartop', 'Cardenas', '22-926-4855', 'ccardenascd@unblog.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (447, 'Ulrika', 'Barltrop', 'Treker', '08-644-2420', 'utrekerce@purevolume.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (448, 'Ted', 'Fansy', 'Benettolo', '26-030-9833', 'tbenettolocf@dyndns.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (449, 'Mellisent', 'Heatly', null, '32-346-8589', 'mshyrescg@rambler.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (450, 'Ardyth', 'Dowse', 'Tomkiss', '24-864-0557', 'atomkissch@tripadvisor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (451, 'Derril', 'Diprose', 'Wayne', '43-540-1994', 'dwayneci@yahoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (452, 'Carley', 'Dymond', 'Bille', '10-254-6318', 'cbillecj@huffingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (453, 'Golda', 'Boam', 'Okie', '05-162-7634', 'gokieck@networkadvertising.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (454, 'Les', 'Stooke', null, '51-891-7835', 'lleguaycl@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (455, 'Viv', 'Ebdon', 'Summerfield', '39-225-4082', 'vsummerfieldcm@desdev.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (456, 'Averill', 'Stonhard', 'Le Brun', '78-689-1703', 'alebruncn@eventbrite.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (457, 'Rene', 'Boneham', 'Bramall', '22-054-2278', 'rbramallco@tripadvisor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (458, 'Lyndy', 'Kiellor', null, '93-446-9909', 'lkoubekcp@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (459, 'Wolfy', 'Sambeck', 'Gligorijevic', '63-578-3127', 'wgligorijeviccq@surveymonkey.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (460, 'Aurea', 'Spelsbury', null, '46-148-1378', 'adalessandrocr@fotki.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (461, 'Marlie', 'Brodhead', null, '28-275-2584', 'mphilcockcs@bbc.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (462, 'Margarete', 'Pfeifer', 'Halpeine', '11-604-8089', 'mhalpeinect@naver.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (463, 'Frankie', 'Kinder', 'Cruces', '40-884-9291', 'fcrucescu@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (464, 'Tyler', 'Micheu', 'Iddiens', '99-703-7771', 'tiddienscv@fema.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (465, 'Gussie', 'Hevner', null, '81-584-7654', 'gbrandassicw@jugem.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (466, 'Jemima', 'Skae', 'O''Caine', '84-041-3361', 'jocainecx@tiny.cc', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (467, 'Darsey', 'Adamkiewicz', 'Gligorijevic', '51-303-2583', 'dgligorijeviccy@cafepress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (468, 'Shaylyn', 'Hubback', 'Cambridge', '52-152-7207', 'scambridgecz@rediff.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (469, 'Anet', 'Sidebottom', 'Potzold', '62-635-8707', 'apotzoldd0@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (470, 'Amaleta', 'Patillo', 'Klampk', '08-917-2203', 'aklampkd1@yellowbook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (471, 'Junie', 'Astall', 'Bottle', '88-007-5296', 'jbottled2@alibaba.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (472, 'Shirline', 'Entwhistle', 'Dalrymple', '44-933-6474', 'sdalrympled3@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (473, 'Fabio', 'Stobie', 'Pollack', '16-565-7316', 'fpollackd4@google.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (474, 'Gabriell', 'Maude', 'Rance', '34-342-5063', 'granced5@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (475, 'Keane', 'Hastings', 'Iacoviello', '99-426-9804', 'kiacoviellod6@wikispaces.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (476, 'Diandra', 'McIlwraith', 'Roth', '94-829-8188', 'drothd7@ow.ly', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (477, 'Alfi', 'MacCarlich', null, '92-438-3457', 'arodgmand8@latimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (478, 'Way', 'Roberson', 'Herreros', '69-284-6562', 'wherrerosd9@bigcartel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (479, 'Woodrow', 'Limon', 'Ten Broek', '06-626-0584', 'wtenbroekda@princeton.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (480, 'Virginie', 'Smallpeace', 'Willoughby', '80-737-4009', 'vwilloughbydb@soundcloud.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (481, 'Farleigh', 'Kybbye', null, '37-769-4308', 'fskeletondc@msn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (482, 'Jenna', 'Riden', 'Marden', '87-237-7931', 'jmardendd@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (483, 'Dela', 'Bratton', 'Chadderton', '75-556-3691', 'dchaddertonde@hud.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (484, 'Keith', 'Corderoy', 'Emslie', '00-355-0103', 'kemsliedf@surveymonkey.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (485, 'Salem', 'Hellewell', 'Edgeon', '07-281-9728', 'sedgeondg@sphinn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (486, 'Tanney', 'Littlemore', 'Neilands', '22-153-9608', 'tneilandsdh@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (487, 'Cirilo', 'Gimber', 'Mussared', '22-882-4902', 'cmussareddi@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (488, 'Emlyn', 'Dragon', null, '72-422-6233', 'eillingsworthdj@wufoo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (489, 'Horten', 'Lippitt', null, '48-425-5131', 'hmelvindk@tamu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (490, 'Gustie', 'Janodet', 'McAteer', '02-985-0639', 'gmcateerdl@wsj.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (491, 'Nicholle', 'Dewsnap', null, '79-085-2338', 'nbabardm@creativecommons.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (492, 'Katina', 'Greer', 'Gaitskill', '61-579-4657', 'kgaitskilldn@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (493, 'Lyndsay', 'Songist', 'Kiendl', '63-994-8699', 'lkiendldo@ft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (494, 'Hakim', 'Beedie', 'Fenner', '65-039-1819', 'hfennerdp@netlog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (495, 'Aridatha', 'Wolfart', null, '80-462-9908', 'apeplowdq@netvibes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (496, 'Denny', 'Swalough', 'Wonter', '92-625-1312', 'dwonterdr@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (497, 'Yorker', 'Dalmon', null, '72-182-8717', 'yknightsds@harvard.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (498, 'Ewen', 'Keyme', 'Le Grand', '40-554-5562', 'elegranddt@buzzfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (499, 'Sancho', 'Faircley', 'Swinburne', '36-909-2863', 'sswinburnedu@biblegateway.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (500, 'Alwin', 'Sarfass', 'Gleader', '07-574-2093', 'agleaderdv@themeforest.net', null);
