insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (1, 'Florrie', 'Ruddick', 'Stubbe', '89-788-1869', 'fstubbe0@g.co', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (2, 'Arabela', 'O''Cannon', 'Sexton', '22-594-3608', 'asexton1@tumblr.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (3, 'Cyrus', 'Aaronson', 'Riccio', '59-104-7466', 'criccio2@bbb.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (4, 'Josy', 'Doudney', 'Haresnaip', '97-620-9489', 'jharesnaip3@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (5, 'Kean', 'Lasham', 'Nijssen', '79-931-3770', 'knijssen4@squarespace.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (6, 'Gregoire', 'Menpes', 'Keward', '63-678-4805', 'gkeward5@walmart.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (7, 'Missy', 'Harmeston', 'Elmes', '10-805-2074', 'melmes6@etsy.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (8, 'Marie-ann', 'Hills', 'Cancellieri', '84-853-3682', 'mcancellieri7@typepad.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (9, 'Lawrence', 'Affleck', null, '15-231-2723', 'ldohmann8@abc.net.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (10, 'Woodie', 'Tethcote', 'Lott', '00-691-1173', 'wlott9@google.com.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (11, 'Gaye', 'Keppel', 'Sindle', '41-314-1928', 'gsindlea@yahoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (12, 'Bryanty', 'Winsiowiecki', 'Pyrton', '80-392-0104', 'bpyrtonb@webeden.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (13, 'Vassily', 'Doodney', 'Flacke', '30-486-1643', 'vflackec@t-online.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (14, 'Hamilton', 'Danovich', 'Towey', '70-563-0348', 'htoweyd@army.mil', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (15, 'Berkeley', 'Jori', null, '45-793-9171', 'bcreasye@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (16, 'Moll', 'Fernandes', 'Goodlett', '85-722-9166', 'mgoodlettf@clickbank.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (17, 'Kaja', 'Mitchley', 'Castledine', '04-471-3578', 'kcastledineg@unblog.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (18, 'Tammie', 'Ditchett', 'Spencook', '68-920-8325', 'tspencookh@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (19, 'Valerye', 'Cubitt', 'Aland', '25-979-3275', 'valandi@stumbleupon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (20, 'Sosanna', 'Boynes', 'Tapner', '23-760-3297', 'stapnerj@dagondesign.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (21, 'Nathan', 'Baudino', 'Lanchbery', '60-317-8561', 'nlanchberyk@123-reg.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (22, 'Ilyse', 'Congrave', 'Steels', '86-882-5868', 'isteelsl@pcworld.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (23, 'Deeyn', 'Hinchshaw', 'Chaim', '53-681-2370', 'dchaimm@washingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (24, 'Sebastiano', 'Leaman', 'Wratten', '65-350-6423', 'swrattenn@prlog.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (25, 'Dorena', 'Trustey', null, '78-539-8703', 'dvasiljevico@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (26, 'Hersh', 'McGaugie', 'Mitford', '80-105-2480', 'hmitfordp@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (27, 'Sandro', 'Proppers', 'Lorkin', '35-419-9299', 'slorkinq@dailymail.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (28, 'Christy', 'Almond', null, '30-084-8333', 'cloransr@whitehouse.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (29, 'Joleen', 'Lawry', null, '31-352-1335', 'jprews@instagram.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (30, 'Dennis', 'Haysham', null, '02-233-7639', 'dhovet@java.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (31, 'Marcela', 'Worssam', 'Lovel', '35-150-4079', 'mlovelu@oracle.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (32, 'Dur', 'Mizzen', null, '49-281-4615', 'dodreainv@moonfruit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (33, 'Kristian', 'Scotfurth', 'Aleksahkin', '76-252-5957', 'kaleksahkinw@shareasale.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (34, 'Mead', 'Kitteridge', 'Garrow', '57-983-9831', 'mgarrowx@a8.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (35, 'Valerye', 'Bertlin', null, '89-767-0806', 'vhubandy@boston.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (36, 'Edeline', 'Samber', 'Hedau', '59-571-7192', 'ehedauz@ow.ly', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (37, 'Nomi', 'De Malchar', 'Foggo', '68-616-0804', 'nfoggo10@pen.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (38, 'Vanessa', 'Tann', 'Bache', '37-434-3450', 'vbache11@jimdo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (39, 'Marleen', 'Dymott', 'Cassar', '58-543-8309', 'mcassar12@psu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (40, 'Barbabra', 'Wildbore', 'Trett', '68-319-6276', 'btrett13@delicious.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (41, 'Blakeley', 'Merrell', 'L''Episcopio', '20-159-5146', 'blepiscopio14@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (42, 'Rourke', 'Turner', 'Hartford', '21-055-9413', 'rhartford15@delicious.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (43, 'Kelsi', 'Ketteringham', 'Peskin', '22-482-3476', 'kpeskin16@squarespace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (44, 'Cleveland', 'Benny', 'Daly', '61-420-9750', 'cdaly17@phoca.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (45, 'Rhys', 'Novill', 'Polsin', '92-811-9200', 'rpolsin18@army.mil', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (46, 'Field', 'Cammomile', 'Grabb', '98-595-5702', 'fgrabb19@paginegialle.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (47, 'Fawn', 'Antony', 'Gagen', '40-390-2400', 'fgagen1a@wikispaces.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (48, 'D''arcy', 'Dourin', 'Dackombe', '42-915-9547', 'ddackombe1b@cdc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (49, 'Falito', 'Fremantle', 'Aslum', '85-082-2330', 'faslum1c@stumbleupon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (50, 'Elliott', 'Witherspoon', null, '53-984-8478', 'ekiessel1d@mlb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (51, 'Fara', 'Dionsetti', 'Vezey', '90-140-7778', 'fvezey1e@google.es', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (52, 'Gilbert', 'Agius', null, '72-689-6589', 'gtoffts1f@oakley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (53, 'Nicolette', 'Sushams', 'Phillpotts', '91-225-7427', 'nphillpotts1g@microsoft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (54, 'Jamil', 'Addams', 'Napper', '76-295-2483', 'jnapper1h@ezinearticles.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (55, 'Abbott', 'Salan', 'Mabley', '36-571-0234', 'amabley1i@craigslist.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (56, 'Pepito', 'Duigan', 'Nissle', '07-118-3125', 'pnissle1j@netvibes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (57, 'Seamus', 'Grenshiels', 'Perassi', '05-870-7317', 'sperassi1k@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (58, 'Chrissy', 'Manville', 'Guiducci', '00-134-9466', 'cguiducci1l@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (59, 'Moe', 'Roj', 'Sale', '33-895-3678', 'msale1m@cloudflare.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (60, 'Birgitta', 'Wildt', 'Drewery', '62-569-6895', 'bdrewery1n@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (61, 'Lynsey', 'Rockcliffe', 'Crucetti', '33-613-7774', 'lcrucetti1o@edublogs.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (62, 'Gottfried', 'Ollarenshaw', 'Morland', '20-097-8104', 'gmorland1p@jigsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (63, 'Noella', 'Figin', 'MacCathay', '01-867-3731', 'nmaccathay1q@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (64, 'Wilbert', 'Yendall', 'Romagosa', '68-706-3256', 'wromagosa1r@un.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (65, 'Haslett', 'Zecchetti', 'Exall', '39-921-9150', 'hexall1s@edublogs.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (66, 'Neville', 'Petrovic', 'Coppard', '56-735-5953', 'ncoppard1t@google.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (67, 'Mylo', 'Ferres', 'Ashcroft', '62-573-8026', 'mashcroft1u@xinhuanet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (68, 'Neel', 'Goldster', 'Meiklejohn', '66-941-3542', 'nmeiklejohn1v@reuters.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (69, 'Matthew', 'Argo', null, '43-541-0305', 'mcuxon1w@forbes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (70, 'Tamarra', 'Peterken', 'Gaines', '12-223-5624', 'tgaines1x@taobao.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (71, 'Shelbi', 'Van de Velde', 'Tetford', '62-976-0626', 'stetford1y@smh.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (72, 'Sarina', 'Guiu', 'Darrach', '50-982-1944', 'sdarrach1z@rediff.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (73, 'Wilburt', 'Wankling', 'Kollatsch', '53-504-7097', 'wkollatsch20@1688.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (74, 'Dur', 'Lampard', 'Lemmon', '58-538-8872', 'dlemmon21@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (75, 'Almeria', 'Novelli', 'Bedrosian', '43-217-8628', 'abedrosian22@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (76, 'Tanny', 'Sambidge', 'MacCartan', '92-185-2818', 'tmaccartan23@freewebs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (77, 'Kerrin', 'Robelin', 'Roach', '80-408-6042', 'kroach24@blogtalkradio.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (78, 'Raye', 'Fairlaw', null, '90-426-6275', 'rtoffoloni25@istockphoto.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (79, 'Grace', 'Fearne', null, '07-010-3865', 'ggauvain26@cdc.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (80, 'Winthrop', 'Kyttor', 'Franceschelli', '98-340-7175', 'wfranceschelli27@va.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (81, 'Egor', 'Moorerud', 'Mulmuray', '13-145-0285', 'emulmuray28@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (82, 'Tilda', 'Haverty', 'Ioannou', '59-291-6319', 'tioannou29@wiley.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (83, 'Theressa', 'Beville', 'Pretti', '92-466-7782', 'tpretti2a@slate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (84, 'Laetitia', 'Bandey', 'Bendel', '18-241-9096', 'lbendel2b@sciencedaily.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (85, 'Idette', 'Wallworth', 'Mendoza', '63-853-6176', 'imendoza2c@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (86, 'Austina', 'Minigo', null, '38-462-9861', 'abrockie2d@jigsy.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (87, 'Kathlin', 'Emanueli', 'MacLaverty', '89-449-8805', 'kmaclaverty2e@samsung.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (88, 'Merrili', 'Adlam', 'Grabiec', '32-584-6328', 'mgrabiec2f@mediafire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (89, 'Harland', 'Fourmy', 'Yexley', '38-831-9007', 'hyexley2g@shutterfly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (90, 'Willi', 'Nowlan', null, '90-401-5832', 'wcorfield2h@theatlantic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (91, 'Chrissie', 'Gathercoal', 'Strippel', '03-781-2069', 'cstrippel2i@sfgate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (92, 'Gregoor', 'Hallin', null, '80-219-8024', 'ggood2j@discuz.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (93, 'Lacy', 'Barenski', 'Piens', '69-657-8831', 'lpiens2k@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (94, 'Jase', 'Comsty', 'Vogt', '93-412-1533', 'jvogt2l@patch.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (95, 'Gerhardine', 'Poulglais', 'Iacabucci', '91-285-6800', 'giacabucci2m@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (96, 'Win', 'Rijkeseis', 'Burnsyde', '27-624-9090', 'wburnsyde2n@eventbrite.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (97, 'Rolfe', 'Kubal', 'Di Biaggi', '66-839-7399', 'rdibiaggi2o@biblegateway.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (98, 'Leona', 'Timothy', null, '07-701-0134', 'lmcanellye2p@liveinternet.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (99, 'Robbi', 'Bredgeland', 'Letten', '14-572-2963', 'rletten2q@unc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (100, 'Ellene', 'Maddie', 'Copozio', '37-952-7404', 'ecopozio2r@cbsnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (101, 'Uta', 'Donaghie', 'Duiged', '27-520-7897', 'uduiged2s@over-blog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (102, 'Rosie', 'Fyers', 'Spatarul', '54-678-1262', 'rspatarul2t@baidu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (103, 'Dolores', 'Tarquinio', 'Baudin', '99-616-7666', 'dbaudin2u@bravesites.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (104, 'Vlad', 'Hofner', 'Buston', '32-313-7863', 'vbuston2v@theguardian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (105, 'Maryrose', 'Paoli', 'Tumbridge', '55-944-2728', 'mtumbridge2w@yale.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (106, 'Reade', 'Manus', 'Josefsson', '07-715-0212', 'rjosefsson2x@businessweek.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (107, 'Kennedy', 'Whitworth', null, '88-856-3863', 'koveril2y@t-online.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (108, 'Bronny', 'Sugge', 'Andreaccio', '65-017-2668', 'bandreaccio2z@spotify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (109, 'Beale', 'Reina', 'Stedman', '94-424-8834', 'bstedman30@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (110, 'Gabey', 'Moquin', 'Deuss', '96-833-4369', 'gdeuss31@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (111, 'Gabie', 'MacCart', 'Abramchik', '52-961-3393', 'gabramchik32@sphinn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (112, 'Sidoney', 'Ragborne', 'Trevan', '59-811-4308', 'strevan33@plala.or.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (113, 'Denney', 'Knowlden', 'Shawe', '95-286-9446', 'dshawe34@soundcloud.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (114, 'Gannon', 'Bannester', 'Gorgen', '31-247-8160', 'ggorgen35@msu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (115, 'Rhodia', 'Ivic', 'Key', '43-644-6815', 'rkey36@gov.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (116, 'Prudence', 'Knevet', 'Greader', '46-268-2662', 'pgreader37@cdbaby.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (117, 'Jemimah', 'Kivlin', null, '09-052-5742', 'jgladwell38@linkedin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (118, 'Erhard', 'McFadzean', null, '21-795-6855', 'epleasants39@businessinsider.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (119, 'Bernadette', 'Coxon', 'O''Concannon', '31-728-4325', 'boconcannon3a@paginegialle.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (120, 'Marybeth', 'Langlais', 'Hirche', '74-229-9616', 'mhirche3b@scientificamerican.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (121, 'Ursula', 'Hirtz', 'De Dantesie', '86-494-3528', 'udedantesie3c@godaddy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (122, 'Arty', 'Vaudin', 'Lilleyman', '30-400-5559', 'alilleyman3d@typepad.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (123, 'Verna', 'Ovenell', 'Loach', '30-239-6659', 'vloach3e@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (124, 'Jeralee', 'Dalgleish', 'Chidgey', '32-872-9777', 'jchidgey3f@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (125, 'Melodee', 'Wimsett', 'Chasle', '71-961-6087', 'mchasle3g@ebay.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (126, 'Britte', 'Ling', null, '58-387-4392', 'bchatburn3h@fema.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (127, 'Ferris', 'Boshers', 'Undrell', '92-182-1423', 'fundrell3i@edublogs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (128, 'Gannon', 'Gloucester', null, '12-465-1973', 'ghowlett3j@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (129, 'Atlanta', 'Hensmans', null, '33-988-3699', 'adarragh3k@sogou.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (130, 'Linell', 'Margiotta', 'McLukie', '58-422-7590', 'lmclukie3l@blogs.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (131, 'Sybila', 'Cowgill', 'Nester', '74-561-5430', 'snester3m@ft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (132, 'Atlante', 'Broggetti', null, '76-887-7365', 'ajeskins3n@msu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (133, 'Mikael', 'Cadwaladr', 'Vizor', '63-349-3929', 'mvizor3o@springer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (134, 'Eleanora', 'Escoffrey', 'Harriagn', '70-051-9109', 'eharriagn3p@storify.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (135, 'Lilia', 'Enrietto', null, '52-626-5675', 'ltinn3q@hao123.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (136, 'Guinna', 'McIllroy', 'Brazener', '54-261-5280', 'gbrazener3r@creativecommons.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (137, 'Rodie', 'Erie', 'Dumphy', '75-467-4370', 'rdumphy3s@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (138, 'Lucita', 'Southon', 'Hillan', '10-038-6478', 'lhillan3t@edublogs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (139, 'Harmonie', 'Maskelyne', 'Bumpas', '93-812-8838', 'hbumpas3u@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (140, 'Kelbee', 'Fetter', null, '90-658-0485', 'kastley3v@cmu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (141, 'Carolynn', 'Labrom', null, '36-808-4964', 'ccostar3w@economist.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (142, 'Shawnee', 'Soppeth', null, '41-910-0106', 'svinsen3x@360.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (143, 'Trude', 'Gatrill', null, '03-850-2200', 'tdeathe3y@tmall.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (144, 'Lief', 'Hrus', null, '82-988-9983', 'lhendin3z@blogs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (145, 'Troy', 'Goshawk', 'Esche', '08-186-7136', 'tesche40@tinypic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (146, 'Aldis', 'Liddell', 'Lalley', '64-073-5337', 'alalley41@bbb.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (147, 'Charmian', 'Underdown', 'Esler', '60-073-7197', 'cesler42@alibaba.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (148, 'Trumann', 'Belcher', 'Neighbour', '54-362-9192', 'tneighbour43@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (149, 'Shandra', 'Death', 'Halward', '04-150-9844', 'shalward44@freewebs.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (150, 'Kelley', 'Kolin', 'Reay', '44-836-6470', 'kreay45@slideshare.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (151, 'Zechariah', 'Sobtka', 'Pogson', '63-505-9492', 'zpogson46@google.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (152, 'Bella', 'Rawcliff', 'Giraldo', '54-962-5853', 'bgiraldo47@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (153, 'Matty', 'Ventum', 'O''Cannon', '09-111-9885', 'mocannon48@hatena.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (154, 'Dun', 'Swigger', 'Hrihorovich', '54-969-8085', 'dhrihorovich49@cnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (155, 'Jens', 'Quinton', 'O''Sheeryne', '52-050-2206', 'josheeryne4a@prlog.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (156, 'Harlen', 'Mochan', null, '35-036-0115', 'hdadda4b@squidoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (157, 'Rutherford', 'Edwins', 'Fraser', '39-085-7528', 'rfraser4c@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (158, 'Marmaduke', 'Tallant', 'Bruckental', '08-629-2699', 'mbruckental4d@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (159, 'Gerianna', 'Carmel', null, '00-987-5925', 'gcamfield4e@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (160, 'Lesley', 'Deakes', null, '90-377-4740', 'lsaben4f@a8.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (161, 'Laureen', 'Eastmead', null, '73-475-4359', 'lcicchelli4g@tripod.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (162, 'Jolie', 'Casetti', 'La Croce', '78-943-0187', 'jlacroce4h@hc360.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (163, 'Eddy', 'Ballentime', 'Choke', '46-610-4101', 'echoke4i@sbwire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (164, 'Jeniffer', 'Pincott', 'Sor', '47-974-3527', 'jsor4j@nih.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (165, 'Lonny', 'Phizacklea', 'Klaassens', '81-202-7872', 'lklaassens4k@free.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (166, 'Helge', 'Brunetti', 'Urwen', '81-932-1761', 'hurwen4l@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (167, 'Benson', 'Llopis', null, '02-399-1495', 'bbayfield4m@cnbc.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (168, 'Emlynne', 'Curnnokk', 'MacAllester', '38-741-8285', 'emacallester4n@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (169, 'Stevana', 'Jakobsson', 'Mackley', '83-270-8238', 'smackley4o@dedecms.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (170, 'Irina', 'De Vaar', 'Kloss', '72-721-1241', 'ikloss4p@acquirethisname.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (171, 'Toinette', 'Joincey', 'Gomer', '75-791-5021', 'tgomer4q@ustream.tv', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (172, 'Artemus', 'Popelay', 'Tissier', '10-647-5610', 'atissier4r@google.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (173, 'Isacco', 'Connal', 'Gresly', '54-442-0185', 'igresly4s@skyrock.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (174, 'Berkly', 'Clougher', 'Innocenti', '74-057-5756', 'binnocenti4t@merriam-webster.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (175, 'Frasquito', 'Fylan', 'Meads', '78-497-9052', 'fmeads4u@va.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (176, 'Sammy', 'Ormes', 'Stang-Gjertsen', '29-654-4506', 'sstanggjertsen4v@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (177, 'Hephzibah', 'Kemster', 'Wormell', '87-689-6648', 'hwormell4w@blogger.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (178, 'Glennis', 'Tille', 'Mazzei', '54-446-8737', 'gmazzei4x@nymag.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (179, 'Kellia', 'Humpherston', 'Propper', '93-697-2891', 'kpropper4y@printfriendly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (180, 'Lezlie', 'Annies', 'Holtaway', '05-720-6397', 'lholtaway4z@imageshack.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (181, 'Laurie', 'Ridde', 'Torbeck', '06-824-5547', 'ltorbeck50@cornell.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (182, 'Giselbert', 'Silber', 'Nursey', '96-697-0167', 'gnursey51@geocities.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (183, 'Jemima', 'Slatter', 'Berrington', '92-914-8008', 'jberrington52@umich.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (184, 'Kristin', 'Topper', 'Bisp', '53-725-3796', 'kbisp53@sfgate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (185, 'Vikky', 'Tonn', 'Cyseley', '77-718-3640', 'vcyseley54@mayoclinic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (186, 'Helsa', 'Chominski', 'Chang', '69-964-4352', 'hchang55@seesaa.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (187, 'Mommy', 'Demer', 'Jendrach', '23-925-5032', 'mjendrach56@mit.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (188, 'Cheslie', 'Zuanelli', null, '48-809-7307', 'cgilbey57@theglobeandmail.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (189, 'Ethyl', 'Emlin', null, '26-293-4542', 'ewhitford58@theguardian.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (190, 'Bliss', 'Huitson', 'Durling', '05-623-6203', 'bdurling59@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (191, 'Morrie', 'Bousler', 'Osanne', '24-566-0630', 'mosanne5a@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (192, 'Saidee', 'Major', 'Pylkynyton', '81-162-4788', 'spylkynyton5b@sun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (193, 'Isador', 'Treffrey', 'Skirling', '10-261-7969', 'iskirling5c@google.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (194, 'Kali', 'Byrch', 'Aitchinson', '83-804-6633', 'kaitchinson5d@mozilla.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (195, 'Antoine', 'Cherrison', 'Maylam', '67-206-3769', 'amaylam5e@sciencedaily.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (196, 'Lazare', 'Riccardelli', 'Hise', '72-656-1972', 'lhise5f@wisc.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (197, 'Nanete', 'Graeber', 'Parnall', '12-570-8000', 'nparnall5g@gmpg.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (198, 'Rutger', 'Quarrington', 'Koenen', '82-704-1932', 'rkoenen5h@cisco.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (199, 'Ashil', 'Forsey', 'Tubb', '51-877-5775', 'atubb5i@theguardian.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (200, 'Louella', 'Trenchard', 'Strainge', '00-084-9183', 'lstrainge5j@wisc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (201, 'Reina', 'Kubas', 'Order', '66-022-6503', 'rorder5k@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (202, 'Clementia', 'Knowller', 'Aleksic', '71-745-6259', 'caleksic5l@wix.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (203, 'Reggie', 'Goodlett', 'Silburn', '97-604-7425', 'rsilburn5m@skyrock.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (204, 'Junette', 'Dyble', 'Plumbe', '85-771-4740', 'jplumbe5n@lulu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (205, 'Clea', 'Tollet', 'Apedaile', '27-389-5651', 'capedaile5o@rakuten.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (206, 'Lion', 'Wandrey', null, '41-237-6622', 'lmattea5p@yahoo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (207, 'Codie', 'Lisamore', 'Udey', '96-836-2926', 'cudey5q@shutterfly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (208, 'Van', 'Allsopp', 'Goulter', '42-405-1925', 'vgoulter5r@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (209, 'Jolie', 'Fosdyke', 'Sorbie', '20-446-8203', 'jsorbie5s@howstuffworks.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (210, 'Krystal', 'Shawdforth', 'Andresen', '86-378-7400', 'kandresen5t@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (211, 'Leora', 'Manwell', 'Malek', '79-522-2690', 'lmalek5u@pcworld.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (212, 'Ferdinanda', 'Petroselli', 'Medlin', '21-667-2602', 'fmedlin5v@woothemes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (213, 'Matelda', 'Croal', null, '23-877-9965', 'mmcsparran5w@chron.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (214, 'Odessa', 'Dixon', 'Rollitt', '11-160-0452', 'orollitt5x@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (215, 'Waylin', 'Mettetal', 'Sharphurst', '32-595-1894', 'wsharphurst5y@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (216, 'Lon', 'Gilhoolie', 'Brandli', '82-699-6468', 'lbrandli5z@amazon.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (217, 'Karolina', 'Cordero', 'Sigmund', '41-360-0647', 'ksigmund60@seattletimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (218, 'Danita', 'Phettis', null, '40-767-5529', 'dborthwick61@macromedia.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (219, 'Jozef', 'Cowland', 'Leyburn', '53-702-5005', 'jleyburn62@slashdot.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (220, 'Arvin', 'Cushe', 'Pulham', '12-686-3890', 'apulham63@mozilla.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (221, 'Gael', 'Caplis', 'Sowood', '85-289-9577', 'gsowood64@g.co', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (222, 'Stan', 'Morat', 'Vallance', '97-734-2172', 'svallance65@amazonaws.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (223, 'Saba', 'Rowe', 'Gerardi', '93-314-1382', 'sgerardi66@wordpress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (224, 'Marla', 'Enrietto', null, '02-424-4671', 'mhefferon67@printfriendly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (225, 'Adelheid', 'Covet', 'Brecher', '96-562-2783', 'abrecher68@netscape.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (226, 'Banky', 'Shorte', 'Amies', '15-425-3084', 'bamies69@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (227, 'Ursulina', 'Hartopp', 'Gunstone', '12-251-3720', 'ugunstone6a@ft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (228, 'Lucie', 'Yesenin', 'Hendron', '29-398-9832', 'lhendron6b@ox.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (229, 'Rafaela', 'Malthus', 'Rosenwasser', '18-612-5608', 'rrosenwasser6c@slashdot.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (230, 'Ronny', 'Edards', 'Rohan', '08-572-1383', 'rrohan6d@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (231, 'Zitella', 'Fairman', 'Grandin', '63-334-2762', 'zgrandin6e@ucsd.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (232, 'Salmon', 'Pelzer', 'Baudino', '38-405-1672', 'sbaudino6f@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (233, 'Melania', 'Newarte', 'Wingar', '35-254-7918', 'mwingar6g@economist.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (234, 'Vinson', 'Dregan', 'Laytham', '56-828-2485', 'vlaytham6h@icio.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (235, 'Kristy', 'Najara', 'Giovannacc@i', '81-794-6783', 'kgiovannacci6i@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (236, 'Kellen', 'Ainger', 'Heamus', '66-458-2310', 'kheamus6j@oaic.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (237, 'Jeffry', 'Pahl', 'Kernan', '01-313-9316', 'jkernan6k@economist.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (238, 'Benny', 'Lanaway', 'Westmorland', '63-080-8914', 'bwestmorland6l@huffingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (239, 'Carissa', 'Crebo', 'Quigg', '37-314-2443', 'cquigg6m@symantec.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (240, 'Murdoch', 'Emer', 'Barette', '35-544-1083', 'mbarette6n@ucoz.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (241, 'Griffin', 'Grent', 'Chesson', '01-303-4544', 'gchesson6o@squidoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (242, 'Lief', 'Kagan', 'Draaisma', '14-096-0816', 'ldraaisma6p@mit.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (243, 'Wain', 'Mandy', 'Peppard', '18-595-5550', 'wpeppard6q@youku.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (244, 'Diarmid', 'Ridings', 'Brennan', '81-014-7807', 'dbrennan6r@auda.org.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (245, 'Marian', 'Schade', 'Titta', '84-277-0178', 'mtitta6s@youku.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (246, 'Bone', 'Darton', 'Masson', '03-489-5800', 'bmasson6t@privacy.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (247, 'Rhonda', 'Kenchington', 'Entwhistle', '01-650-5033', 'rentwhistle6u@scribd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (248, 'Cristina', 'Andersen', 'Atte-Stone', '79-023-3296', 'cattestone6v@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (249, 'Kelby', 'Rigmand', 'Gilluley', '49-422-0541', 'kgilluley6w@yolasite.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (250, 'Northrop', 'Josofovitz', 'Culbert', '51-239-9600', 'nculbert6x@sfgate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (251, 'Hewitt', 'Stowte', 'Gierek', '09-110-7711', 'hgierek6y@wikispaces.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (252, 'Gabey', 'Lutty', 'Boch', '32-359-9244', 'gboch6z@epa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (253, 'Shelba', 'Jolliman', 'Bartomieu', '06-257-8836', 'sbartomieu70@cnbc.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (254, 'Benn', 'Jendrassik', 'Dinnage', '94-183-3939', 'bdinnage71@washingtonpost.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (255, 'Leeann', 'Alessandrucci', 'McCallister', '94-884-7173', 'lmccallister72@prweb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (256, 'Marena', 'Ruslen', 'Loveguard', '40-022-8280', 'mloveguard73@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (257, 'Jodie', 'Ludlamme', null, '73-951-5148', 'jstrete74@unicef.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (258, 'Jobie', 'Lebond', 'Morsey', '61-668-9416', 'jmorsey75@nymag.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (259, 'Haley', 'Weddell', null, '83-995-0879', 'hwhiscard76@163.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (260, 'Micheil', 'Bockler', 'Reuss', '64-769-6853', 'mreuss77@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (261, 'Bronny', 'Foldes', 'Ubsdall', '59-154-5954', 'bubsdall78@scribd.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (262, 'Alejandra', 'Gawen', 'Tregear', '77-431-1170', 'atregear79@marriott.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (263, 'Indira', 'Watts', null, '34-129-9131', 'igunter7a@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (264, 'Peri', 'Aysh', null, '84-462-8845', 'paveson7b@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (265, 'Jeri', 'Baylis', 'Scoffham', '32-006-2825', 'jscoffham7c@harvard.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (266, 'Theodore', 'Norvell', 'Draysay', '72-907-1542', 'tdraysay7d@fda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (267, 'Curr', 'Floch', 'Sprigin', '17-935-0021', 'csprigin7e@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (268, 'Dare', 'Heaven', 'Ambrosi', '09-817-5218', 'dambrosi7f@studiopress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (269, 'Chrissy', 'Hedaux', 'Burgane', '32-485-0716', 'cburgane7g@fda.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (270, 'Essie', 'Belfitt', 'Richfield', '96-136-7732', 'erichfield7h@si.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (271, 'Jed', 'Westfield', 'Crucetti', '25-446-4687', 'jcrucetti7i@rakuten.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (272, 'Levin', 'Daelman', 'O''Loinn', '33-348-8001', 'loloinn7j@github.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (273, 'Gris', 'Howe', 'Bonifazio', '01-997-0287', 'gbonifazio7k@sun.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (274, 'Teodorico', 'Lille', 'Eccles', '10-280-3747', 'teccles7l@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (275, 'Lorrie', 'Lergan', 'Enrietto', '46-640-4717', 'lenrietto7m@vk.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (276, 'Dido', 'Tomicki', 'Casin', '45-405-2720', 'dcasin7n@ucoz.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (277, 'Phelia', 'Aspinell', 'Schoenleiter', '63-720-9775', 'pschoenleiter7o@sphinn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (278, 'Ursulina', 'Zupa', null, '28-182-1444', 'uwonfor7p@google.nl', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (279, 'Brant', 'MacVaugh', 'Charlotte', '18-862-3527', 'bcharlotte7q@psu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (280, 'Louisa', 'Le Sieur', 'Smalman', '97-270-8590', 'lsmalman7r@people.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (281, 'Hazlett', 'Stanesby', 'Rosini', '35-739-8115', 'hrosini7s@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (282, 'Margalit', 'Dolligon', null, '21-486-9487', 'mmacgebenay7t@census.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (283, 'Tynan', 'Caulliere', 'Foster', '32-555-1409', 'tfoster7u@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (284, 'Lowell', 'Lester', 'Sego', '39-008-0664', 'lsego7v@intel.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (285, 'Brear', 'De Witt', 'Bonallack', '06-586-4908', 'bbonallack7w@pbs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (286, 'Llewellyn', 'Sebright', 'Humerstone', '27-869-3193', 'lhumerstone7x@google.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (287, 'Dall', 'Sirey', 'Iowarch', '15-219-0998', 'diowarch7y@acquirethisname.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (288, 'Cheri', 'Porter', 'Vispo', '53-474-1217', 'cvispo7z@google.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (289, 'Dickie', 'Neachell', 'Denisot', '91-326-5471', 'ddenisot80@newyorker.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (290, 'Gwyn', 'Cumpsty', 'Fidler', '69-138-1961', 'gfidler81@simplemachines.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (291, 'Joyous', 'Lavis', 'Tomadoni', '31-610-4766', 'jtomadoni82@blogger.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (292, 'Nelli', 'Falk', 'Dietz', '88-524-4464', 'ndietz83@jimdo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (293, 'Verene', 'McGroarty', 'De Bernardis', '51-896-0594', 'vdebernardis84@ning.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (294, 'Karissa', 'Hardinge', 'McCutheon', '23-640-8003', 'kmccutheon85@cargocollective.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (295, 'Rafaello', 'Kupper', 'Farlham', '27-331-3788', 'rfarlham86@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (296, 'Holden', 'Dorcey', 'Ivanonko', '98-236-4615', 'hivanonko87@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (297, 'Jayme', 'Melliard', 'Cawthry', '50-078-8952', 'jcawthry88@pen.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (298, 'Lauryn', 'Moyer', 'Celloni', '51-359-2887', 'lcelloni89@jugem.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (299, 'Marrissa', 'Tomowicz', 'Roxby', '47-832-6662', 'mroxby8a@ovh.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (300, 'Ida', 'Ghiroldi', 'Readitt', '62-975-4464', 'ireaditt8b@domainmarket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (301, 'Murielle', 'Quainton', 'Stredwick', '62-901-5744', 'mstredwick8c@booking.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (302, 'Gale', 'Utridge', 'Frill', '58-700-0345', 'gfrill8d@drupal.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (303, 'Penelopa', 'Fillis', 'Havis', '18-139-0501', 'phavis8e@umn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (304, 'Cy', 'Kuhwald', 'Kolakovic', '17-515-0867', 'ckolakovic8f@dion.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (305, 'Cthrine', 'Abramov', null, '71-465-9445', 'cdaouse8g@zdnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (306, 'Cassandra', 'Stagge', null, '30-392-6215', 'cremmers8h@state.tx.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (307, 'Daven', 'Aidler', 'Habbijam', '67-064-8102', 'dhabbijam8i@zdnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (308, 'Dorelle', 'Quickenden', 'Strutz', '89-775-0369', 'dstrutz8j@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (309, 'Ursulina', 'Allwright', 'Raiston', '37-418-4390', 'uraiston8k@dmoz.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (310, 'Evangelina', 'Torns', null, '08-656-6331', 'emcging8l@gizmodo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (311, 'Lyssa', 'Uwins', 'Abbie', '54-141-9496', 'labbie8m@alibaba.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (312, 'Darcy', 'Oloman', 'Coultas', '97-555-2580', 'dcoultas8n@unblog.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (313, 'Hillary', 'Rathke', 'Moir', '38-004-7973', 'hmoir8o@wordpress.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (314, 'Khalil', 'Belsey', 'Shackelton', '15-386-1214', 'kshackelton8p@dot.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (315, 'Edie', 'Crawford', 'Krates', '90-045-9611', 'ekrates8q@hud.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (316, 'Rochelle', 'Checklin', 'Wale', '56-914-5271', 'rwale8r@ehow.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (317, 'Shurwood', 'Vamplers', 'Heibl', '67-279-8524', 'sheibl8s@pbs.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (318, 'Esra', 'Rawsthorne', 'Cornil', '24-079-6492', 'ecornil8t@whitehouse.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (319, 'Norbie', 'Frayn', 'Pollen', '73-292-4120', 'npollen8u@biblegateway.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (320, 'Chrystal', 'Venus', 'Ondra', '52-508-7331', 'condra8v@hao123.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (321, 'Mickie', 'Ferriere', 'Pedersen', '40-228-6487', 'mpedersen8w@simplemachines.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (322, 'Mariette', 'Goford', 'Perle', '11-845-3026', 'mperle8x@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (323, 'Blondelle', 'Crampin', null, '44-550-7359', 'bhartop8y@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (324, 'Andrey', 'Melloy', 'Dagnan', '83-178-6096', 'adagnan8z@howstuffworks.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (325, 'Percy', 'Gallally', 'Bardwall', '69-143-6929', 'pbardwall90@ask.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (326, 'Johnathon', 'Izakoff', 'Eamer', '51-372-7436', 'jeamer91@loc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (327, 'Desi', 'Milborn', 'Fudger', '56-959-8386', 'dfudger92@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (328, 'Carroll', 'Minci', null, '74-882-0108', 'cduer93@i2i.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (329, 'Parker', 'Curro', 'Pennoni', '87-248-7217', 'ppennoni94@vistaprint.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (330, 'Melisent', 'Abilowitz', 'Abrahamsen', '75-117-9269', 'mabrahamsen95@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (331, 'Ronny', 'Shwalbe', 'Semaine', '55-642-1653', 'rsemaine96@omniture.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (332, 'Todd', 'Yarrington', 'Stainland', '01-549-8606', 'tstainland97@webmd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (333, 'Ibrahim', 'McMorran', null, '79-493-7737', 'ioneal98@nih.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (334, 'Augustine', 'Coll', null, '97-375-7812', 'awhardley99@unc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (335, 'Costa', 'Cosford', null, '41-712-4132', 'ccumberbatch9a@mit.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (336, 'Tulley', 'Winspurr', 'Bromige', '90-283-0688', 'tbromige9b@feedburner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (337, 'Camellia', 'Benardette', null, '05-008-1982', 'cscragg9c@naver.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (338, 'Bibi', 'Shave', 'Veneur', '66-482-2009', 'bveneur9d@cloudflare.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (339, 'Stephi', 'Dunstone', 'Karleman', '77-225-0695', 'skarleman9e@noaa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (340, 'Jemimah', 'Eves', 'Barthram', '39-987-8403', 'jbarthram9f@ifeng.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (341, 'Clovis', 'Sheed', 'Pavett', '80-899-6806', 'cpavett9g@hugedomains.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (342, 'Si', 'Woollard', 'Fould', '12-260-9871', 'sfould9h@a8.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (343, 'Herta', 'Ridge', 'Millthorpe', '22-626-0517', 'hmillthorpe9i@miibeian.gov.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (344, 'Hedwiga', 'Garahan', 'McEachern', '32-946-7781', 'hmceachern9j@tinyurl.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (345, 'Franny', 'Anger', 'Meneer', '91-643-7228', 'fmeneer9k@europa.eu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (346, 'Kippy', 'Rolance', null, '96-919-6019', 'kcatlin9l@ca.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (347, 'Tammi', 'Wiley', 'Moncrefe', '34-995-6377', 'tmoncrefe9m@google.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (348, 'Cathee', 'Plaster', 'Vose', '23-895-1226', 'cvose9n@hp.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (349, 'Mellisa', 'Simukov', null, '52-006-8291', 'mwoodrooffe9o@ibm.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (350, 'Silva', 'Harrill', 'Ouldcott', '56-364-8122', 'souldcott9p@opera.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (351, 'Reggi', 'Thorpe', 'Enriquez', '44-824-8238', 'renriquez9q@e-recht24.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (352, 'Torie', 'Martina', null, '06-363-7448', 'tcornfield9r@theglobeandmail.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (353, 'Jennee', 'Pistol', 'Grossier', '00-584-5750', 'jgrossier9s@dedecms.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (354, 'Keary', 'Boulder', null, '07-552-2613', 'kfewings9t@free.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (355, 'Emmalynn', 'Kondrat', 'MacKissack', '84-813-4036', 'emackissack9u@reddit.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (356, 'Kizzee', 'Gulk', 'Jeandel', '35-491-9662', 'kjeandel9v@sogou.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (357, 'Fleur', 'Northern', 'Johann', '97-667-1819', 'fjohann9w@upenn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (358, 'Duky', 'Bratcher', 'Loyley', '65-366-3523', 'dloyley9x@shutterfly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (359, 'Amalita', 'Rockhill', 'Sayles', '23-772-3861', 'asayles9y@google.com.hk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (360, 'Noach', 'Worpole', 'Horribine', '09-676-6824', 'nhorribine9z@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (361, 'Carlyle', 'Deacock', 'Parmer', '57-954-1264', 'cparmera0@altervista.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (362, 'Oralia', 'MacGuffie', null, '12-424-3343', 'obailya1@usa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (363, 'Morie', 'Bench', 'Gurry', '79-037-9238', 'mgurrya2@macromedia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (364, 'Tobie', 'Kinavan', null, '26-221-3629', 'tscollanda3@angelfire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (365, 'Lou', 'Slyman', 'Gabbitus', '00-830-0715', 'lgabbitusa4@va.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (366, 'Birgitta', 'Tarver', null, '16-583-6360', 'bpoachera5@themeforest.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (367, 'Thorvald', 'Storer', 'Nutbean', '74-462-3595', 'tnutbeana6@spiegel.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (368, 'Celia', 'Delieu', null, '78-631-0810', 'ccadda7@cocolog-nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (369, 'Wes', 'Hatherleigh', 'Stuckford', '11-901-9239', 'wstuckforda8@altervista.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (370, 'Randa', 'Emlen', 'Pakeman', '69-132-2191', 'rpakemana9@google.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (371, 'Myrvyn', 'Tansly', 'Senten', '96-298-2012', 'msentenaa@bloglovin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (372, 'Aeriel', 'Kinkead', 'Lumly', '57-650-7345', 'alumlyab@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (373, 'Shandra', 'Cockshot', 'Kindleysides', '11-887-1154', 'skindleysidesac@about.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (374, 'Arabella', 'Newstead', null, '32-830-8021', 'abraunead@hexun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (375, 'Gabie', 'Clell', 'Fleisch', '04-322-5726', 'gfleischae@typepad.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (376, 'Raquela', 'Haslin', 'Beal', '40-116-0387', 'rbealaf@stanford.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (377, 'Aggie', 'Learmouth', 'Halbeard', '36-724-9360', 'ahalbeardag@artisteer.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (378, 'Ami', 'Finnie', 'Feldbau', '59-258-1801', 'afeldbauah@dell.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (379, 'Nealon', 'Worton', 'Kahler', '60-967-6465', 'nkahlerai@so-net.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (380, 'Ethelbert', 'Tolussi', 'Treven', '65-449-0496', 'etrevenaj@squidoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (381, 'Sella', 'Kirdsch', null, '78-543-1298', 'santalak@51.la', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (382, 'Reena', 'Covert', 'Smalecombe', '16-291-0594', 'rsmalecombeal@disqus.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (383, 'Shaw', 'Aleshintsev', 'Nolton', '75-864-2220', 'snoltonam@facebook.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (384, 'Antonella', 'Cortes', 'Kapelhof', '76-652-8146', 'akapelhofan@imdb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (385, 'Elbertine', 'Boxe', 'O''Dennehy', '76-122-3456', 'eodennehyao@cyberchimps.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (386, 'Catriona', 'Moggle', 'Irdale', '97-882-5128', 'cirdaleap@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (387, 'Georg', 'Hackinge', 'Divine', '74-471-1204', 'gdivineaq@unesco.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (388, 'Janek', 'Dmitriev', 'Knighton', '19-664-3095', 'jknightonar@wired.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (389, 'Deedee', 'Henrique', 'Cromley', '33-232-6438', 'dcromleyas@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (390, 'Alvira', 'Cotton', 'McCluskey', '46-417-7547', 'amccluskeyat@omniture.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (391, 'Georgine', 'Trathan', 'Windross', '24-235-0747', 'gwindrossau@sciencedirect.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (392, 'Abbott', 'Mulhill', 'Dubois', '39-303-7162', 'aduboisav@ow.ly', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (393, 'Guthrie', 'Jeannon', 'Rivelon', '19-914-6318', 'grivelonaw@tinypic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (394, 'Alli', 'Rama', 'O''Hallagan', '71-670-2957', 'aohallaganax@thetimes.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (395, 'Morgan', 'Murrill', 'Stouther', '18-385-4644', 'mstoutheray@wikipedia.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (396, 'Bette-ann', 'Lambrechts', 'Hutson', '75-853-1047', 'bhutsonaz@tripadvisor.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (397, 'Constantia', 'Fillary', 'Misson', '20-609-8064', 'cmissonb0@hostgator.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (398, 'Giselle', 'Kneaphsey', 'Ingrey', '42-336-4052', 'gingreyb1@microsoft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (399, 'Riccardo', 'Ambrose', 'Juares', '63-769-3941', 'rjuaresb2@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (400, 'Gerry', 'Kayzer', 'Pennings', '83-877-8514', 'gpenningsb3@soundcloud.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (401, 'Hilary', 'Wycliffe', 'Prangnell', '83-690-5710', 'hprangnellb4@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (402, 'Rich', 'Avramchik', 'Benesevich', '78-311-8811', 'rbenesevichb5@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (403, 'Neille', 'Devenny', 'Wilhelmy', '89-127-3884', 'nwilhelmyb6@time.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (404, 'Evyn', 'Castanho', 'Clayworth', '02-116-2107', 'eclayworthb7@shutterfly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (405, 'Henrieta', 'Maciaszczyk', 'Ludye', '86-371-4879', 'hludyeb8@blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (406, 'Audi', 'Claige', 'Coslett', '06-304-7362', 'acoslettb9@rakuten.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (407, 'Sher', 'Eiler', 'Booker', '50-131-3603', 'sbookerba@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (408, 'Drusy', 'Pickrell', 'Vittet', '16-615-5459', 'dvittetbb@sogou.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (409, 'Horacio', 'Ferber', 'Yeowell', '48-823-8538', 'hyeowellbc@exblog.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (410, 'Amata', 'Rohmer', null, '80-844-9535', 'adakinbd@amazon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (411, 'Bart', 'Jobbins', 'Boldison', '98-559-7794', 'bboldisonbe@cyberchimps.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (412, 'Erinn', 'Hum', 'Lorans', '04-527-7001', 'eloransbf@usa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (413, 'Letti', 'Bello', 'Snewin', '42-549-2351', 'lsnewinbg@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (414, 'Krisha', 'Belson', 'Lorenc', '63-611-2212', 'klorencbh@booking.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (415, 'Pat', 'Gawthrope', 'Houseley', '84-308-3289', 'phouseleybi@sogou.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (416, 'Andres', 'Mirfield', 'Coopland', '70-610-4762', 'acooplandbj@mlb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (417, 'Jamie', 'Kike', 'McInulty', '23-565-4949', 'jmcinultybk@nifty.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (418, 'Addi', 'Corley', 'Infantino', '72-744-2894', 'ainfantinobl@wiley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (419, 'Hamid', 'Gatteridge', 'Baskett', '41-713-1366', 'hbaskettbm@salon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (420, 'Lelia', 'Shipton', 'Odgers', '14-238-6185', 'lodgersbn@google.com.hk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (421, 'Miner', 'Blankley', 'Postance', '31-890-9142', 'mpostancebo@unicef.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (422, 'Kippie', 'Sherrock', 'Lidgard', '43-096-5963', 'klidgardbp@illinois.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (423, 'Anna-diana', 'Marde', 'Boyles', '46-105-6558', 'aboylesbq@infoseek.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (424, 'Ricki', 'Kellog', 'Challener', '71-875-6778', 'rchallenerbr@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (425, 'Blakeley', 'Paulusch', 'Headech', '18-345-0743', 'bheadechbs@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (426, 'Farly', 'Knighton', null, '22-440-0265', 'fdredgebt@issuu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (427, 'Iseabal', 'Knotte', 'Monckman', '17-423-1882', 'imonckmanbu@virginia.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (428, 'Edi', 'Poundesford', 'Verchambre', '60-054-3112', 'everchambrebv@hatena.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (429, 'Gun', 'Ellis', 'Woolaston', '29-652-7354', 'gwoolastonbw@photobucket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (430, 'Jen', 'Liffey', null, '21-932-0387', 'jmouattbx@i2i.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (431, 'Amelia', 'McGilben', 'Hazel', '97-434-9761', 'ahazelby@oaic.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (432, 'Carlota', 'Venus', 'Abelson', '64-519-3520', 'cabelsonbz@buzzfeed.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (433, 'Ben', 'Shine', null, '45-638-9454', 'bbanglec0@dell.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (434, 'Elise', 'Meriguet', 'Greenan', '52-998-6823', 'egreenanc1@slashdot.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (435, 'Athena', 'Ridolfi', 'Ambrozewicz', '92-014-9042', 'aambrozewiczc2@bing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (436, 'Rupert', 'Wareing', 'Blondelle', '70-998-9994', 'rblondellec3@reference.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (437, 'Janette', 'Arne', 'Seggie', '36-595-4518', 'jseggiec4@trellian.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (438, 'Bamby', 'McLeod', null, '12-339-0267', 'bwynterc5@samsung.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (439, 'Nona', 'McNickle', 'Dunkerton', '18-572-0769', 'ndunkertonc6@kickstarter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (440, 'Amalea', 'Riatt', null, '87-794-2482', 'amaccallesterc7@typepad.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (441, 'Edward', 'Bidgod', 'Knowlden', '97-762-5489', 'eknowldenc8@washington.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (442, 'Brittni', 'Mohun', 'O''Lagen', '64-548-4940', 'bolagenc9@networkadvertising.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (443, 'Federica', 'Staziker', 'Rizzo', '96-586-3152', 'frizzoca@infoseek.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (444, 'Nap', 'Shubotham', 'Blissitt', '35-860-9336', 'nblissittcb@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (445, 'Cindee', 'Roddam', 'Pierrepoint', '85-462-3025', 'cpierrepointcc@angelfire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (446, 'Sandy', 'Carloni', 'Darbyshire', '49-327-2674', 'sdarbyshirecd@sphinn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (447, 'Nerita', 'Lionel', 'Abbs', '66-794-0785', 'nabbsce@java.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (448, 'Sheelagh', 'Porkiss', 'Allender', '40-643-0425', 'sallendercf@theguardian.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (449, 'Marv', 'Iddens', 'Kibbye', '85-204-9448', 'mkibbyecg@nature.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (450, 'Natalina', 'Bambrick', 'Learie', '91-379-1364', 'nleariech@cafepress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (451, 'Riccardo', 'Jeaycock', null, '08-803-1833', 'rcustedci@berkeley.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (452, 'Margit', 'Bunney', null, '43-857-4651', 'mslackcj@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (453, 'Janifer', 'Gurry', 'Lightwood', '63-007-6692', 'jlightwoodck@desdev.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (454, 'Noni', 'Whitewood', 'Drummer', '91-730-1942', 'ndrummercl@smh.com.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (455, 'Fran', 'Sanderson', 'Wimbridge', '05-424-0019', 'fwimbridgecm@marriott.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (456, 'Natal', 'Dabel', 'Ashbee', '25-099-8616', 'nashbeecn@cisco.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (457, 'Johanna', 'Tie', 'Walworche', '04-140-9776', 'jwalworcheco@phpbb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (458, 'Marsh', 'Ugolini', 'Nucator', '95-074-5137', 'mnucatorcp@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (459, 'Thorndike', 'Ambrogiotti', 'Sercombe', '84-434-7966', 'tsercombecq@nbcnews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (460, 'Patsy', 'Gorsse', 'Goodright', '62-934-6314', 'pgoodrightcr@npr.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (461, 'Marco', 'Arlet', 'Fraser', '50-644-6024', 'mfrasercs@cargocollective.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (462, 'Georgette', 'Meadus', 'Eacle', '47-929-4669', 'geaclect@addthis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (463, 'Cirstoforo', 'Kembley', 'Donett', '93-059-6448', 'cdonettcu@howstuffworks.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (464, 'Quinta', 'Ockleshaw', 'Issett', '86-370-9898', 'qissettcv@diigo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (465, 'Deny', 'Callf', 'Bithell', '05-398-3214', 'dbithellcw@unesco.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (466, 'Roobbie', 'Hurworth', null, '79-751-3462', 'raynscombecx@example.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (467, 'Lenee', 'Luckcock', null, '22-954-8173', 'lshiptoncy@topsy.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (468, 'Caleb', 'Arguile', 'Hardesty', '68-123-8057', 'chardestycz@admin.ch', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (469, 'Inga', 'Girogetti', 'Willcott', '56-422-3677', 'iwillcottd0@flickr.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (470, 'Hestia', 'Blaydes', null, '18-458-8039', 'hstandishd1@time.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (471, 'Rebecca', 'Smetoun', 'Beauly', '45-792-2638', 'rbeaulyd2@economist.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (472, 'Dionisio', 'Rustan', 'Hartright', '74-121-1455', 'dhartrightd3@netvibes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (473, 'Filberto', 'Kyneton', null, '00-651-4870', 'fcissend4@xrea.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (474, 'Packston', 'Conlaund', 'Chelsom', '64-239-7045', 'pchelsomd5@yandex.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (475, 'Madeline', 'Sinnatt', 'Coleyshaw', '89-630-8204', 'mcoleyshawd6@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (476, 'Maegan', 'Ruilton', 'Kerrigan', '83-925-5983', 'mkerrigand7@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (477, 'Erica', 'Spawforth', null, '87-059-8360', 'esilburnd8@tmall.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (478, 'Maribeth', 'Kingsnod', 'Lilleyman', '43-119-5861', 'mlilleymand9@bravesites.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (479, 'Raeann', 'Mattack', 'Fay', '53-859-9501', 'rfayda@wordpress.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (480, 'Violetta', 'Hatliffe', 'Jancic', '81-024-7403', 'vjancicdb@hatena.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (481, 'Aleta', 'Rennocks', 'Buckell', '18-751-2115', 'abuckelldc@blogger.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (482, 'Karie', 'Yushankin', 'Ahren', '09-915-4779', 'kahrendd@jugem.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (483, 'Ebba', 'Waugh', null, '51-293-0939', 'ebothamde@sohu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (484, 'Jillene', 'Andreu', 'Battin', '38-550-3572', 'jbattindf@flavors.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (485, 'Alia', 'Ughelli', null, '20-756-1963', 'alindmandg@tiny.cc', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (486, 'Dyanna', 'Bulfit', null, '30-304-5013', 'dortellsdh@nature.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (487, 'Lothario', 'Andrieu', null, '10-153-1003', 'lredwindi@cbc.ca', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (488, 'Leta', 'Bloodworthe', 'Lipman', '99-412-0546', 'llipmandj@google.nl', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (489, 'Christopher', 'Patillo', 'Sucre', '81-074-9200', 'csucredk@1688.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (490, 'Fianna', 'Leate', null, '13-810-5574', 'flobleydl@cafepress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (491, 'Inna', 'Letchford', 'Craythorn', '14-786-3255', 'icraythorndm@webnode.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (492, 'Shelley', 'Fernanando', 'Souness', '77-111-4688', 'ssounessdn@sina.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (493, 'Walsh', 'Van Waadenburg', 'Zarb', '91-701-8533', 'wzarbdo@loc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (494, 'Gardy', 'Calcutt', null, '31-659-0088', 'gmatejovskydp@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (495, 'Brand', 'Cafferky', 'Hunday', '35-440-5231', 'bhundaydq@va.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (496, 'Carolina', 'Joskovitch', 'Griffen', '29-951-4114', 'cgriffendr@icio.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (497, 'Whitby', 'Brannigan', 'Goodfellowe', '28-757-3316', 'wgoodfelloweds@g.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (498, 'Kippie', 'Holleran', 'Proske', '79-962-9066', 'kproskedt@google.com.hk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (499, 'Mac', 'McCrachen', 'Durrant', '18-852-1100', 'mdurrantdu@nature.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (500, 'Raddie', 'Kienle', 'Remirez', '61-472-7621', 'rremirezdv@friendfeed.com', null);
