insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (1, 'Lynnell', 'Bush', 'Bracco', '55-033-8076', 'lbracco0@studiopress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (2, 'Ronalda', 'Stannas', 'Hartop', '48-248-5362', 'rhartop1@bing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (3, 'Arda', 'Birchill', 'Forte', '82-314-4031', 'aforte2@cdc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (4, 'Serena', 'Baudou', null, '28-860-0170', 'schristoffersen3@boston.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (5, 'Celene', 'Dufer', 'Outright', '56-937-2122', 'coutright4@e-recht24.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (6, 'Libbie', 'St Pierre', null, '83-089-6652', 'lperone5@smugmug.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (7, 'Thomasa', 'Lowther', 'Sanpere', '34-938-6741', 'tsanpere6@samsung.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (8, 'Joye', 'McClymont', null, '07-847-7009', 'jlamberton7@msn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (9, 'Andrus', 'Pavier', 'Gyenes', '36-480-7134', 'agyenes8@cafepress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (10, 'Janot', 'Roycroft', 'Sangster', '22-163-3178', 'jsangster9@github.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (11, 'Tamqrah', 'Lamble', null, '01-246-4550', 'tchaslesa@wsj.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (12, 'Cherie', 'Hummerston', 'Fishleigh', '68-831-1783', 'cfishleighb@amazon.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (13, 'Coleen', 'Spoole', 'Pavlishchev', '93-743-0108', 'cpavlishchevc@amazon.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (14, 'Agnese', 'Meriton', 'Smalcombe', '49-342-8228', 'asmalcombed@mail.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (15, 'Alys', 'Potten', 'Barnett', '26-183-6250', 'abarnette@google.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (16, 'Justen', 'Whardley', 'Tomkin', '21-273-2690', 'jtomkinf@youtu.be', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (17, 'Rebe', 'Cowhig', 'McLaughlin', '24-371-7588', 'rmclaughling@abc.net.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (18, 'Arte', 'Showen', 'Lydiatt', '22-149-8742', 'alydiatth@state.tx.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (19, 'Guillaume', 'Coley', 'Bromby', '78-561-4749', 'gbrombyi@amazonaws.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (20, 'Susan', 'Pudge', 'Dukesbury', '37-167-5423', 'sdukesburyj@rambler.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (21, 'Devin', 'Forst', 'Zuppa', '59-753-8376', 'dzuppak@patch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (22, 'Thornie', 'Melburg', 'O'' Shea', '13-834-7662', 'tosheal@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (23, 'Jerrine', 'Sowersby', null, '72-221-9871', 'jtwinamem@sourceforge.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (24, 'Darell', 'Jepp', 'Quigley', '29-131-0727', 'dquigleyn@deliciousdays.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (25, 'Freddy', 'Cardoe', 'Collecott', '14-941-2774', 'fcollecotto@businessinsider.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (26, 'Conny', 'Eltune', 'Scanterbury', '14-499-3853', 'cscanterburyp@cornell.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (27, 'Camel', 'Macguire', 'Dorrins', '58-830-6022', 'cdorrinsq@google.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (28, 'Sterne', 'Kinvan', null, '36-914-2852', 'sambroiser@abc.net.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (29, 'Leoine', 'Cufley', 'Di Lucia', '55-783-7349', 'ldilucias@latimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (30, 'Orelie', 'Side', 'Cuniam', '37-114-6110', 'ocuniamt@cafepress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (31, 'Christabella', 'Fantin', 'Shird', '21-246-0679', 'cshirdu@hexun.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (32, 'Maegan', 'Ovitz', 'Pridham', '87-258-4248', 'mpridhamv@npr.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (33, 'D''arcy', 'Lawrence', 'Petzold', '69-135-4685', 'dpetzoldw@hhs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (34, 'Gale', 'Kirkhouse', 'Tindle', '61-353-4639', 'gtindlex@surveymonkey.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (35, 'Suzie', 'Detoile', 'Bottomley', '01-030-1435', 'sbottomleyy@slideshare.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (36, 'Jodee', 'Findlay', 'MacConnell', '40-468-1586', 'jmacconnellz@myspace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (37, 'Bobbette', 'Whitmore', 'Shefton', '75-131-0606', 'bshefton10@state.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (38, 'Jo', 'Kelshaw', 'Petherick', '05-223-2926', 'jpetherick11@wunderground.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (39, 'Marne', 'Brayn', 'Lavielle', '40-450-7267', 'mlavielle12@g.co', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (40, 'Amble', 'Millington', 'Yurenev', '03-034-5733', 'ayurenev13@soup.io', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (41, 'Alley', 'Birdseye', 'McTerrelly', '78-586-5343', 'amcterrelly14@amazon.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (42, 'Hill', 'Slite', 'Standering', '72-845-4145', 'hstandering15@utexas.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (43, 'Adelaide', 'Ingraham', 'Gelletly', '61-799-7247', 'agelletly16@edublogs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (44, 'Bev', 'Hamstead', null, '35-621-0162', 'bosler17@reddit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (45, 'Corbin', 'Dendle', null, '13-892-4193', 'cbreit18@shareasale.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (46, 'Bert', 'Gander', null, '61-025-6518', 'bstowell19@adobe.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (47, 'Celestyna', 'Bolf', 'Feldbaum', '77-263-6310', 'cfeldbaum1a@tiny.cc', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (48, 'Zarla', 'Chilver', null, '91-283-3113', 'zjewar1b@mit.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (49, 'Shepperd', 'Wythe', 'Eisak', '73-483-7186', 'seisak1c@netvibes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (50, 'Meriel', 'Fulton', null, '51-026-6001', 'mtaleworth1d@moonfruit.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (51, 'Nanine', 'Keunemann', null, '13-282-8166', 'nalelsandrovich1e@ft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (52, 'Antoine', 'Dagnall', 'O''Fergus', '84-955-8069', 'aofergus1f@unc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (53, 'Monte', 'Kubiczek', 'Sowerby', '74-736-6772', 'msowerby1g@aboutads.info', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (54, 'Kermie', 'Moffet', 'Formoy', '17-694-2136', 'kformoy1h@ed.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (55, 'Joletta', 'Costard', 'Kobiela', '09-865-7426', 'jkobiela1i@yale.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (56, 'Stephenie', 'Sattin', 'Mitchinson', '39-155-7637', 'smitchinson1j@bandcamp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (57, 'Ceciley', 'Tesh', 'Pendered', '88-056-1561', 'cpendered1k@mapquest.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (58, 'Laurie', 'Smallpeace', 'Darnborough', '55-352-9351', 'ldarnborough1l@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (59, 'Christos', 'Ratcliff', 'Clausen', '81-292-1380', 'cclausen1m@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (60, 'Coleman', 'Fogg', 'Newens', '02-886-0823', 'cnewens1n@wix.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (61, 'Mohandas', 'Ilett', 'Blitzer', '41-843-2481', 'mblitzer1o@networkadvertising.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (62, 'Gerda', 'Skehan', 'Clampe', '03-365-5385', 'gclampe1p@nsw.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (63, 'Alva', 'Agglio', 'Mangenot', '92-440-9049', 'amangenot1q@unblog.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (64, 'Tirrell', 'Clixby', 'Goscomb', '87-582-6214', 'tgoscomb1r@com.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (65, 'Ethelin', 'Emps', 'Fosdick', '27-834-3332', 'efosdick1s@360.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (66, 'Boyd', 'Bresnen', 'Gasquoine', '46-641-8864', 'bgasquoine1t@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (67, 'Cori', 'Keems', 'Lindell', '45-514-1195', 'clindell1u@vimeo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (68, 'Laura', 'Fittis', 'Korb', '87-632-1312', 'lkorb1v@wunderground.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (69, 'Aileen', 'Duckerin', 'Bollen', '20-478-1462', 'abollen1w@google.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (70, 'Gary', 'Ram', 'Catteroll', '84-871-4477', 'gcatteroll1x@xinhuanet.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (71, 'Barney', 'Izzat', null, '31-662-1520', 'bjancar1y@blogger.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (72, 'Valerye', 'Canfer', 'Root', '13-017-7398', 'vroot1z@huffingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (73, 'Terese', 'Toyer', null, '49-959-3221', 'tronayne20@bigcartel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (74, 'Val', 'Vollam', null, '81-311-1031', 'vwhittam21@salon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (75, 'Benedikta', 'Tolomei', 'Bowkley', '68-675-4136', 'bbowkley22@bing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (76, 'Emmi', 'Vuittet', 'Casini', '42-758-7997', 'ecasini23@statcounter.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (77, 'Delilah', 'Abrahmer', 'Linsley', '59-087-0997', 'dlinsley24@cocolog-nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (78, 'Urbain', 'Millhill', 'Seiffert', '66-026-3974', 'useiffert25@imgur.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (79, 'Michele', 'Maria', null, '35-963-7494', 'mfinnis26@salon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (80, 'Luise', 'Anstis', null, '84-998-4629', 'ldohmer27@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (81, 'Welbie', 'Ousbie', 'Davidove', '91-748-1975', 'wdavidove28@reuters.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (82, 'Alaster', 'Leiden', 'Skitch', '12-103-7152', 'askitch29@mapy.cz', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (83, 'Junina', 'Greeno', 'Oldacre', '15-564-8570', 'joldacre2a@shinystat.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (84, 'Obed', 'Farleigh', null, '15-901-3972', 'oolivella2b@nationalgeographic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (85, 'Marcellina', 'Luthwood', 'Forcade', '67-035-1526', 'mforcade2c@marketwatch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (86, 'Kaleena', 'Fison', 'Honatsch', '08-189-1986', 'khonatsch2d@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (87, 'Inglebert', 'Plant', 'Kuhlmey', '01-135-6850', 'ikuhlmey2e@techcrunch.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (88, 'Carey', 'McNee', null, '50-219-0614', 'csouthworth2f@apache.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (89, 'Brigid', 'Reye', 'Colisbe', '63-805-1673', 'bcolisbe2g@buzzfeed.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (90, 'Ulla', 'Tilne', 'Arnett', '45-329-5626', 'uarnett2h@upenn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (91, 'Cynde', 'Potteridge', 'Shadbolt', '51-561-9439', 'cshadbolt2i@washington.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (92, 'Mame', 'Fisbburne', 'Oliva', '20-054-1854', 'moliva2j@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (93, 'Lewes', 'Thornhill', 'Paulich', '52-439-8971', 'lpaulich2k@goo.gl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (94, 'Justinn', 'Luther', null, '36-711-2552', 'jbrimman2l@nhs.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (95, 'Dexter', 'Witheridge', 'Corringham', '28-981-6667', 'dcorringham2m@wiley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (96, 'Viola', 'Barrabeale', 'Ledamun', '23-681-4076', 'vledamun2n@state.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (97, 'Jodi', 'Sharpe', 'Gallen', '48-492-0760', 'jgallen2o@google.nl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (98, 'Tremaine', 'Halifax', 'Rangle', '44-322-6000', 'trangle2p@discovery.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (99, 'Arlie', 'Byforth', 'Trill', '15-410-4761', 'atrill2q@webs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (100, 'Flem', 'Godley', 'Faro', '59-185-2703', 'ffaro2r@nhs.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (101, 'Jarad', 'Reace', 'Stobart', '57-789-8224', 'jstobart2s@etsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (102, 'Mycah', 'Gonzalvo', 'Robilliard', '72-078-6817', 'mrobilliard2t@behance.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (103, 'Lory', 'Dummer', 'Loudiane', '78-321-2354', 'lloudiane2u@reuters.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (104, 'Giraldo', 'Shah', 'Feldbau', '65-566-5082', 'gfeldbau2v@sphinn.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (105, 'Arlie', 'Cogger', 'Abela', '11-455-4263', 'aabela2w@craigslist.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (106, 'Marcy', 'Mapis', 'Wem', '35-061-9009', 'mwem2x@un.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (107, 'Gates', 'Gamblin', 'Justun', '72-140-3492', 'gjustun2y@cbslocal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (108, 'Wallache', 'Leman', 'Inwood', '36-281-5307', 'winwood2z@fema.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (109, 'Jarid', 'Melbourne', null, '97-267-2764', 'jcredland30@wikimedia.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (110, 'Dieter', 'Atling', 'Boswell', '74-441-1305', 'dboswell31@miibeian.gov.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (111, 'Coop', 'Curless', null, '81-402-0572', 'crakes32@uol.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (112, 'Jorrie', 'Milner', 'Smurthwaite', '75-033-7619', 'jsmurthwaite33@arizona.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (113, 'Boniface', 'McSweeney', 'Rouke', '92-092-8364', 'brouke34@pbs.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (114, 'Cathe', 'Arnaud', 'Gilstin', '82-923-7537', 'cgilstin35@smh.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (115, 'Priscilla', 'Lydall', 'Tresler', '42-258-3455', 'ptresler36@marriott.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (116, 'Chilton', 'Coultish', 'Cawcutt', '40-583-2108', 'ccawcutt37@instagram.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (117, 'Hendrika', 'Simioni', 'Allbut', '90-415-0505', 'hallbut38@slate.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (118, 'Stacey', 'Chavez', 'Davidai', '20-243-0844', 'sdavidai39@spiegel.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (119, 'Karen', 'Benech', 'Bumpass', '01-445-7729', 'kbumpass3a@nba.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (120, 'Turner', 'Kiledal', null, '44-010-0341', 'tziem3b@ning.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (121, 'Steven', 'Pallaske', null, '76-146-6121', 'sdellcasa3c@google.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (122, 'Zorina', 'Keasley', null, '85-608-1485', 'zcess3d@jimdo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (123, 'Ernestus', 'Bussens', null, '25-798-6434', 'ecollingdon3e@dmoz.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (124, 'Jessamyn', 'Ruffles', 'Pilgrim', '91-636-5180', 'jpilgrim3f@photobucket.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (125, 'Ciro', 'Cinderey', 'Lafont', '96-627-7504', 'clafont3g@adobe.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (126, 'Anderson', 'Wittering', 'Joint', '44-643-9179', 'ajoint3h@merriam-webster.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (127, 'Janos', 'Timperley', 'Swetmore', '71-439-5995', 'jswetmore3i@netlog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (128, 'Tyne', 'Goolding', 'Batman', '62-840-2977', 'tbatman3j@mlb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (129, 'Matt', 'Cawsby', 'Lorie', '30-263-1760', 'mlorie3k@tamu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (130, 'Marci', 'Djorvic', 'Girauld', '66-707-7822', 'mgirauld3l@sciencedirect.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (131, 'Collette', 'Raddon', 'Wooles', '19-377-3190', 'cwooles3m@ebay.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (132, 'Elva', 'Ranson', 'Dunsford', '53-568-6298', 'edunsford3n@oaic.gov.au', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (133, 'Davide', 'Richardsson', 'Harrinson', '20-099-9958', 'dharrinson3o@flavors.me', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (134, 'Eldredge', 'Rigbye', 'Tolussi', '83-508-6316', 'etolussi3p@engadget.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (135, 'Emalia', 'Hollerin', 'Matthew', '88-726-1573', 'ematthew3q@cam.ac.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (136, 'Sydney', 'Wines', 'Szymanzyk', '14-078-1739', 'sszymanzyk3r@google.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (137, 'Merilee', 'Enterlein', 'Arnefield', '75-295-5434', 'marnefield3s@wufoo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (138, 'Christin', 'Petrello', 'Winterborne', '53-459-8124', 'cwinterborne3t@naver.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (139, 'Gawain', 'de Broke', 'Arnould', '78-713-9093', 'garnould3u@dot.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (140, 'Rosemarie', 'Westmerland', 'Tollmache', '90-707-6182', 'rtollmache3v@exblog.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (141, 'Earle', 'Affron', 'Bernocchi', '56-053-1560', 'ebernocchi3w@businesswire.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (142, 'Annette', 'Furphy', 'Kirwood', '46-091-7027', 'akirwood3x@macromedia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (143, 'Prent', 'Turbern', 'Le Conte', '44-460-9756', 'pleconte3y@cyberchimps.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (144, 'Keven', 'Gregson', 'Messager', '41-961-8867', 'kmessager3z@people.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (145, 'Stavros', 'Highwood', 'Menico', '99-850-5457', 'smenico40@cdc.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (146, 'Tandie', 'Maffeo', null, '73-106-1446', 'tlevay41@behance.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (147, 'Wye', 'Stuckey', null, '73-973-3390', 'whalbert42@foxnews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (148, 'Bernete', 'Worling', null, '36-316-9277', 'bfosse43@yellowpages.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (149, 'Roarke', 'Barthrop', 'Gurner', '58-450-5944', 'rgurner44@wikimedia.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (150, 'Jerrie', 'Pie', 'Havoc', '32-943-4915', 'jhavoc45@ucla.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (151, 'Earvin', 'Boulder', 'Woolley', '78-613-5705', 'ewoolley46@princeton.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (152, 'Baillie', 'Clayill', 'Foxen', '17-675-9621', 'bfoxen47@yolasite.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (153, 'Mel', 'Kasting', 'Bartoshevich', '41-645-9182', 'mbartoshevich48@hc360.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (154, 'Jonathon', 'Barbrook', 'Dewen', '15-443-4194', 'jdewen49@psu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (155, 'Ethelyn', 'Simoneau', null, '51-385-2738', 'echucks4a@unicef.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (156, 'Oralia', 'Chesters', 'Went', '32-511-1632', 'owent4b@cnbc.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (157, 'Michel', 'Melby', 'Alfonsetto', '88-689-4880', 'malfonsetto4c@harvard.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (158, 'Magdalen', 'Stannett', 'Kirkby', '31-104-1349', 'mkirkby4d@cafepress.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (159, 'Heinrik', 'Labone', 'Razzell', '88-166-7848', 'hrazzell4e@yahoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (160, 'Grete', 'Zorzutti', 'Jennaway', '56-977-8020', 'gjennaway4f@upenn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (161, 'Antonella', 'Brellin', 'Maha', '53-573-1821', 'amaha4g@japanpost.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (162, 'Natty', 'Dowglass', null, '34-168-9418', 'npaternoster4h@livejournal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (163, 'Glennis', 'Lapenna', 'Scarlin', '07-263-3569', 'gscarlin4i@house.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (164, 'Nadya', 'Pendell', 'Kynvin', '41-376-6331', 'nkynvin4j@icq.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (165, 'Travus', 'Gwilliams', null, '04-734-8567', 'tvonasek4k@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (166, 'Rebecca', 'Soda', null, '79-745-3729', 'rnockalls4l@miibeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (167, 'Maris', 'Frangello', null, '26-043-3947', 'mdyte4m@xing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (168, 'Mirabelle', 'Mulbery', 'Wolfarth', '33-786-9883', 'mwolfarth4n@bloglines.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (169, 'Dela', 'Brierley', 'McGreary', '92-067-6914', 'dmcgreary4o@linkedin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (170, 'Gaylene', 'Enderby', 'Cottingham', '64-653-8164', 'gcottingham4p@google.com.hk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (171, 'Reggy', 'Hairsine', 'Imlacke', '61-071-3950', 'rimlacke4q@ucla.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (172, 'Stephine', 'Luard', 'Chopin', '29-586-4308', 'schopin4r@go.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (173, 'Irita', 'Burhouse', 'Boadby', '24-964-5768', 'iboadby4s@sphinn.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (174, 'Wilow', 'Duplain', 'Kehoe', '48-541-5270', 'wkehoe4t@fastcompany.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (175, 'Harcourt', 'Ventum', 'Worvell', '13-868-8604', 'hworvell4u@vinaora.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (176, 'Shaughn', 'Castlake', 'Tonkinson', '13-867-8705', 'stonkinson4v@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (177, 'Alexis', 'Bullimore', 'Blacksell', '29-934-8465', 'ablacksell4w@posterous.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (178, 'Justin', 'Penrose', 'Dreelan', '02-760-9829', 'jdreelan4x@soundcloud.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (179, 'Burgess', 'Scrimshaw', null, '91-386-7095', 'bwestmancoat4y@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (180, 'Gilberte', 'Skechley', 'Chewter', '12-263-2207', 'gchewter4z@mozilla.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (181, 'Eugenius', 'Grzelak', 'Mackin', '46-979-7806', 'emackin50@amazon.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (182, 'Conway', 'Hartridge', 'Zoephel', '71-484-7501', 'czoephel51@qq.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (183, 'Clary', 'Andrewartha', 'Fishly', '81-327-4676', 'cfishly52@jimdo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (184, 'Daffy', 'Grandison', 'Reynold', '04-440-0132', 'dreynold53@nifty.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (185, 'Erika', 'Fusedale', 'MacFarlan', '78-697-4152', 'emacfarlan54@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (186, 'Eddie', 'Rumble', 'Bissex', '63-179-8025', 'ebissex55@goo.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (187, 'Bondon', 'Tremblett', 'Sproule', '06-448-0465', 'bsproule56@e-recht24.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (188, 'Reube', 'Matijevic', null, '37-784-4358', 'rpardew57@1und1.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (189, 'Darcee', 'Darcy', 'Mitchell', '50-821-3578', 'dmitchell58@blogger.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (190, 'Edin', 'Reijmers', null, '12-143-2132', 'ebockmaster59@google.com.br', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (191, 'Therine', 'Gregoli', null, '35-051-9449', 'thinkley5a@bing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (192, 'Mozelle', 'Bazek', 'Brailsford', '09-313-7579', 'mbrailsford5b@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (193, 'Winn', 'Kidney', 'Lowrie', '30-273-5540', 'wlowrie5c@liveinternet.ru', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (194, 'Nadia', 'Ferentz', 'Giacoppoli', '88-474-6669', 'ngiacoppoli5d@squidoo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (195, 'Adoree', 'Churches', 'Haxby', '72-091-3918', 'ahaxby5e@arizona.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (196, 'Towney', 'Davydochkin', 'Saphin', '56-364-4092', 'tsaphin5f@nationalgeographic.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (197, 'Cinderella', 'Wethey', 'Wagon', '31-149-2312', 'cwagon5g@home.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (198, 'Sinclair', 'Drewet', 'Sankey', '18-851-4452', 'ssankey5h@xrea.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (199, 'Marne', 'Gartland', 'Hazelhurst', '77-034-0787', 'mhazelhurst5i@taobao.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (200, 'Elisabetta', 'Hick', 'Norwood', '85-634-6318', 'enorwood5j@i2i.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (201, 'Ariadne', 'Gwin', null, '54-188-8319', 'afranklin5k@amazon.co.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (202, 'Yvette', 'Hull', 'Hovee', '54-100-5216', 'yhovee5l@ebay.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (203, 'Antonetta', 'Godmer', 'Heath', '75-243-4109', 'aheath5m@shareasale.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (204, 'Laughton', 'Huckster', 'Geake', '01-086-6793', 'lgeake5n@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (205, 'Claudelle', 'Gonzalez', null, '95-812-2980', 'ckeel5o@clickbank.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (206, 'Maximilianus', 'Klousner', null, '69-658-0935', 'mdonkersley5p@yale.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (207, 'Loralie', 'Tuhy', null, '38-348-1311', 'lstatton5q@nba.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (208, 'Malcolm', 'Endrighi', 'Baldocci', '87-681-0705', 'mbaldocci5r@china.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (209, 'Maxie', 'Beaulieu', null, '71-116-1096', 'mwallentin5s@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (210, 'Esmeralda', 'Macro', null, '76-758-9802', 'ehamments5t@umn.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (211, 'Cinderella', 'Brice', 'Killen', '55-169-9783', 'ckillen5u@chicagotribune.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (212, 'Ricky', 'Potebury', 'Lawden', '93-734-2466', 'rlawden5v@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (213, 'Coral', 'St. Louis', null, '52-866-6232', 'ckalderon5w@macromedia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (214, 'Galvin', 'Avon', 'Lintin', '13-892-8581', 'glintin5x@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (215, 'June', 'Wyer', 'Gay', '19-653-9505', 'jgay5y@google.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (216, 'Beau', 'Wroth', null, '78-090-7635', 'bjulian5z@chronoengine.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (217, 'Dorolisa', 'Norcop', 'Dey', '65-794-2388', 'ddey60@imageshack.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (218, 'Perla', 'Clipson', 'Quested', '64-972-4994', 'pquested61@wiley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (219, 'Clerkclaude', 'Krzyzowski', 'Truman', '69-442-7117', 'ctruman62@aol.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (220, 'Beatriz', 'Snelgrove', 'Snoding', '24-262-4404', 'bsnoding63@bloomberg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (221, 'Nealon', 'Althrop', 'Manwaring', '23-407-8789', 'nmanwaring64@msn.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (222, 'Cordell', 'Mullenger', 'Vedishchev', '29-608-8843', 'cvedishchev65@dmoz.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (223, 'Hodge', 'Follit', 'Taborre', '04-479-1635', 'htaborre66@prlog.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (224, 'Hebert', 'Habin', 'Benedyktowicz', '39-098-4085', 'hbenedyktowicz67@gravatar.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (225, 'Lalo', 'Stilgo', null, '70-498-7339', 'lbelliveau68@wsj.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (226, 'Maitilde', 'Piggrem', 'Panchen', '08-304-7643', 'mpanchen69@webnode.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (227, 'Chelsea', 'Brownsill', 'Castagne', '43-288-6872', 'ccastagne6a@pinterest.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (228, 'Lesli', 'Dentith', 'Cogley', '33-450-5610', 'lcogley6b@over-blog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (229, 'Ethel', 'Dutton', 'Waleworke', '54-763-6326', 'ewaleworke6c@smugmug.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (230, 'Jilly', 'Tilburn', 'Cregeen', '47-509-7668', 'jcregeen6d@fastcompany.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (231, 'Gwenora', 'Slyde', 'Pollins', '96-070-1486', 'gpollins6e@4shared.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (232, 'Cornela', 'Vousden', 'Awty', '40-099-7999', 'cawty6f@google.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (233, 'Suzi', 'Iddens', null, '71-424-7842', 'scharlick6g@eepurl.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (234, 'Joella', 'Benitti', 'Grelik', '80-019-4672', 'jgrelik6h@mashable.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (235, 'Lela', 'Jankovsky', null, '59-681-6874', 'lmacnaughton6i@youtube.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (236, 'Aurelea', 'Harp', null, '17-540-8248', 'asey6j@sciencedirect.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (237, 'Jillian', 'Pietesch', 'Jorgensen', '28-078-6531', 'jjorgensen6k@japanpost.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (238, 'Martyn', 'Bagnell', null, '66-151-3845', 'mbeard6l@ucoz.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (239, 'Jeannie', 'Aries', null, '08-800-6237', 'jscocroft6m@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (240, 'Andy', 'Ohm', 'Guidini', '98-414-6067', 'aguidini6n@goodreads.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (241, 'Shea', 'Scanes', 'Gotobed', '93-410-4576', 'sgotobed6o@columbia.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (242, 'Elsie', 'Mackerel', 'Robers', '59-989-5278', 'erobers6p@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (243, 'Robinetta', 'Twentyman', 'Alpine', '50-226-3185', 'ralpine6q@ask.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (244, 'Ulrick', 'Penna', 'Goolden', '29-707-0073', 'ugoolden6r@discovery.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (245, 'Carol-jean', 'Bennetts', 'Ritzman', '56-841-2180', 'critzman6s@cdc.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (246, 'Cora', 'Skelhorn', 'Hodge', '47-863-9798', 'chodge6t@symantec.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (247, 'Johnath', 'Treneman', 'Leacy', '10-729-8225', 'jleacy6u@google.it', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (248, 'Wilburt', 'Hacking', null, '76-960-5098', 'wnehl6v@homestead.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (249, 'Giff', 'Rough', 'Lennon', '36-458-9829', 'glennon6w@behance.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (250, 'Lester', 'Butland', 'Rabjohns', '42-194-3118', 'lrabjohns6x@scientificamerican.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (251, 'Bunni', 'Frankum', null, '37-789-2910', 'bbispo6y@canalblog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (252, 'Victor', 'Ransom', 'Soff', '32-757-0687', 'vsoff6z@nhs.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (253, 'Dolli', 'Korejs', null, '18-693-3091', 'ddorrins70@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (254, 'Vivyanne', 'Dakin', 'Mallender', '80-825-7019', 'vmallender71@creativecommons.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (255, 'Porty', 'Swatman', 'Vine', '67-840-5444', 'pvine72@wikia.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (256, 'Cybil', 'Hebbard', 'Fernan', '41-113-2147', 'cfernan73@mtv.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (257, 'Joy', 'Kadwallider', null, '36-044-9358', 'jescreet74@wiley.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (258, 'Candi', 'Ivankovic', 'Chattelaine', '69-685-4709', 'cchattelaine75@yellowbook.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (259, 'Viole', 'Windebank', 'Scothorne', '22-069-1376', 'vscothorne76@macromedia.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (260, 'Hans', 'Burfield', null, '45-880-2983', 'hprangle77@cnet.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (261, 'Sula', 'Haggett', 'Sumner', '39-809-6092', 'ssumner78@wp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (262, 'Jone', 'Chilles', 'Kennelly', '56-600-6625', 'jkennelly79@vinaora.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (263, 'Rance', 'MacFadzan', null, '25-938-3920', 'rmiddup7a@google.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (264, 'Nat', 'Durran', 'Cakebread', '32-518-7307', 'ncakebread7b@myspace.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (265, 'Alex', 'Trattles', 'Slisby', '04-957-1227', 'aslisby7c@google.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (266, 'Cleve', 'Shilliday', 'Dineges', '89-768-2224', 'cdineges7d@psu.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (267, 'Westbrook', 'Beddard', 'Tantum', '96-759-5594', 'wtantum7e@purevolume.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (268, 'Eran', 'Meiningen', 'Keiling', '17-201-1945', 'ekeiling7f@dailymotion.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (269, 'Noell', 'Mapplebeck', 'Luparti', '74-201-7323', 'nluparti7g@ted.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (270, 'Bridget', 'Filipchikov', 'Vokins', '88-458-8359', 'bvokins7h@nytimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (271, 'Cary', 'Sizzey', 'Stear', '09-578-7399', 'cstear7i@w3.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (272, 'Darill', 'Westphalen', 'Jestico', '87-268-8253', 'djestico7j@slideshare.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (273, 'Neda', 'Noone', 'Ibbett', '17-033-0087', 'nibbett7k@ebay.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (274, 'Corina', 'Dinesen', 'Gussie', '99-621-4740', 'cgussie7l@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (275, 'Loralee', 'Befroy', 'Rames', '61-805-8034', 'lrames7m@sun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (276, 'Serene', 'Le Quesne', 'Elfleet', '60-761-6763', 'selfleet7n@merriam-webster.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (277, 'Billie', 'Colqueran', null, '70-402-6532', 'bholbury7o@rakuten.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (278, 'Stacy', 'Vasnetsov', 'Cecely', '03-579-8414', 'scecely7p@addtoany.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (279, 'Grenville', 'Conaghan', null, '83-848-1835', 'glambourn7q@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (280, 'Octavia', 'Rambadt', 'Howman', '60-506-0161', 'ohowman7r@amazonaws.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (281, 'Alfonso', 'Wilfling', 'Spraggon', '37-652-5088', 'aspraggon7s@tripod.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (282, 'Boigie', 'Fache', 'Allnatt', '07-308-1221', 'ballnatt7t@bbb.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (283, 'Travis', 'Mell', 'Yielding', '43-003-9740', 'tyielding7u@meetup.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (284, 'Kylie', 'Sevin', 'McNish', '56-698-1364', 'kmcnish7v@theglobeandmail.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (285, 'Jonathan', 'Vasenin', null, '62-549-0851', 'jjanca7w@google.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (286, 'Nani', 'Chalmers', 'Eykelhof', '16-513-6299', 'neykelhof7x@shareasale.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (287, 'Clare', 'Dorr', 'Bowton', '33-472-7494', 'cbowton7y@linkedin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (288, 'Marjory', 'Felton', 'East', '70-376-6979', 'meast7z@last.fm', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (289, 'Toni', 'Derye-Barrett', 'Westphalen', '70-014-6752', 'twestphalen80@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (290, 'Doti', 'Menendes', 'Robertet', '25-867-1565', 'drobertet81@technorati.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (291, 'Emmeline', 'Gentile', null, '00-226-9303', 'eclendinning82@bbb.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (292, 'Starr', 'Margrett', 'Benn', '22-029-1196', 'sbenn83@amazon.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (293, 'Prentice', 'Guidelli', 'Clabburn', '30-470-0162', 'pclabburn84@hatena.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (294, 'Iseabal', 'Sumers', 'Scolts', '95-759-6752', 'iscolts85@wiley.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (295, 'Mose', 'Frondt', 'Kenningley', '07-963-0520', 'mkenningley86@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (296, 'Lorrayne', 'Harbard', 'Lillo', '10-602-5855', 'llillo87@sogou.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (297, 'Didi', 'Groves', 'McGroarty', '21-934-4999', 'dmcgroarty88@hexun.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (298, 'Emlynne', 'Croster', 'Norbury', '41-437-8459', 'enorbury89@barnesandnoble.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (299, 'Oralla', 'Beccero', null, '24-023-9145', 'owhatley8a@shutterfly.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (300, 'Cynthia', 'Skerme', 'Mardell', '36-541-1075', 'cmardell8b@seattletimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (301, 'Carri', 'Tickner', 'Rosenschein', '41-703-9076', 'crosenschein8c@google.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (302, 'Linnet', 'Gilloran', 'Lissandre', '63-926-0811', 'llissandre8d@tamu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (303, 'Laurie', 'O''Lynn', 'Allott', '90-155-9230', 'lallott8e@google.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (304, 'Massimiliano', 'Biggs', 'Mazdon', '23-530-8949', 'mmazdon8f@cbsnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (305, 'Bevvy', 'Faughny', 'McIlvenny', '40-377-5382', 'bmcilvenny8g@smh.com.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (306, 'Kendrick', 'Portal', 'Applewhaite', '63-184-2129', 'kapplewhaite8h@senate.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (307, 'Tonnie', 'Ethington', 'Reeveley', '33-916-6473', 'treeveley8i@ovh.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (308, 'Conant', 'Tester', null, '63-104-6748', 'cplayden8j@cam.ac.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (309, 'Odilia', 'Hallitt', 'Sebley', '15-420-7182', 'osebley8k@last.fm', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (310, 'Ronnica', 'Kirby', 'Jeavons', '72-895-3612', 'rjeavons8l@macromedia.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (311, 'Eada', 'Ruddin', null, '86-809-6721', 'evowells8m@miibeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (312, 'Quinn', 'Cherrie', 'Yurtsev', '66-873-4528', 'qyurtsev8n@miitbeian.gov.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (313, 'Bastien', 'Chinn', 'Cuttler', '97-623-7620', 'bcuttler8o@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (314, 'Devy', 'Gosalvez', 'Van Arsdalen', '49-050-4991', 'dvanarsdalen8p@360.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (315, 'Mira', 'Milhench', 'Bosley', '39-123-8439', 'mbosley8q@sitemeter.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (316, 'Farley', 'Maccaig', 'Zoane', '49-195-0929', 'fzoane8r@berkeley.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (317, 'Jacobo', 'Taggart', 'End', '33-016-6646', 'jend8s@facebook.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (318, 'Cal', 'Verdy', null, '88-111-3837', 'cbounds8t@jigsy.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (319, 'Deonne', 'Vanichkov', 'Fernely', '97-867-3199', 'dfernely8u@dagondesign.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (320, 'Imogene', 'Londors', 'Ovitz', '69-017-4915', 'iovitz8v@google.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (321, 'Grethel', 'Ferne', 'Sharrard', '61-957-8573', 'gsharrard8w@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (322, 'Maudie', 'Musicka', 'Fiander', '22-906-2869', 'mfiander8x@toplist.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (323, 'Rutherford', 'Gusticke', 'Henrie', '39-487-2029', 'rhenrie8y@ftc.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (324, 'Tamera', 'Katt', 'Eustanch', '62-328-4877', 'teustanch8z@yahoo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (325, 'Nobe', 'Hegley', 'Norrey', '53-564-0231', 'nnorrey90@amazon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (326, 'Tobin', 'Redfern', 'Kempston', '36-721-4666', 'tkempston91@imgur.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (327, 'Mendy', 'Vossgen', 'Heinschke', '59-737-1380', 'mheinschke92@amazon.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (328, 'Kath', 'Mager', 'Scoyne', '14-521-8324', 'kscoyne93@oaic.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (329, 'Ericha', 'Aggiss', null, '34-508-5527', 'esilvester94@nationalgeographic.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (330, 'Mady', 'Gidden', null, '32-888-0852', 'mtrevena95@mysql.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (331, 'Huntlee', 'Furst', 'Jennison', '47-128-0410', 'hjennison96@tinyurl.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (332, 'Morey', 'Hanster', null, '02-541-4467', 'mlees97@linkedin.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (333, 'Raimondo', 'Littleton', 'Habbergham', '78-714-8400', 'rhabbergham98@state.tx.us', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (334, 'Carlin', 'Sutterby', 'Seggie', '21-892-8607', 'cseggie99@surveymonkey.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (335, 'Yolande', 'Vice', null, '92-086-8815', 'ymithan9a@ucsd.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (336, 'Aubrey', 'Luetkemeyers', 'Corrett', '18-070-5327', 'acorrett9b@ft.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (337, 'Meggy', 'Ropkes', 'Leadbitter', '70-875-7137', 'mleadbitter9c@hexun.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (338, 'Creigh', 'MacCall', 'Jemmett', '47-999-3527', 'cjemmett9d@foxnews.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (339, 'Carolee', 'Greystoke', null, '77-918-7444', 'ckyllford9e@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (340, 'Sean', 'Wickson', 'Aguilar', '99-744-2115', 'saguilar9f@netscape.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (341, 'Electra', 'Vize', 'Mattiazzi', '11-086-2296', 'emattiazzi9g@bandcamp.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (342, 'Evania', 'Howson', 'Orme', '14-066-1465', 'eorme9h@admin.ch', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (343, 'Boris', 'Louiset', null, '19-129-4116', 'baird9i@skype.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (344, 'Skippie', 'Oldfield-Cherry', null, '96-752-8417', 'ssall9j@free.fr', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (345, 'Ailbert', 'Kestian', 'Godwyn', '02-379-2412', 'agodwyn9k@livejournal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (346, 'Pavla', 'Northcliffe', 'Fladgate', '10-467-1614', 'pfladgate9l@ucsd.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (347, 'Rosalind', 'Kidstone', 'Beynke', '85-166-6971', 'rbeynke9m@cnbc.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (348, 'Stefanie', 'Bauchop', 'Vakhrushev', '47-945-0795', 'svakhrushev9n@statcounter.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (349, 'Templeton', 'Stygall', 'Casellas', '34-239-0438', 'tcasellas9o@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (350, 'Pietrek', 'Artingstall', 'Cloake', '46-714-7908', 'pcloake9p@dagondesign.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (351, 'Moria', 'Duell', 'Spoerl', '99-459-6135', 'mspoerl9q@opensource.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (352, 'Ancell', 'Rozea', null, '21-783-2756', 'azorener9r@fc2.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (353, 'Zara', 'Madle', null, '99-464-0865', 'zyuryev9s@yahoo.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (354, 'Bellina', 'Cristofalo', null, '43-368-1096', 'bzolini9t@wiley.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (355, 'Cairistiona', 'Diemer', 'Vinas', '18-680-2167', 'cvinas9u@nydailynews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (356, 'Margareta', 'Ferryman', 'Rabley', '06-577-6898', 'mrabley9v@nyu.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (357, 'Marrissa', 'Moore', 'Mohring', '32-235-5571', 'mmohring9w@arstechnica.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (358, 'Agretha', 'Fontin', 'Atwater', '51-624-3291', 'aatwater9x@naver.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (359, 'Roxane', 'Maultby', null, '84-739-7614', 'rlipp9y@dion.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (360, 'Giffy', 'Douglass', 'Tiffney', '32-241-7824', 'gtiffney9z@hibu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (361, 'Darrelle', 'Featherstonhaugh', 'Milligan', '11-352-5904', 'dmilligana0@icio.us', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (362, 'Kayley', 'Duignan', null, '70-179-1636', 'kbaynona1@furl.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (363, 'Rickie', 'Brands', 'Coules', '04-920-0081', 'rcoulesa2@clickbank.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (364, 'Scott', 'Tredger', 'Castells', '38-666-7781', 'scastellsa3@utexas.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (365, 'Jaquelyn', 'Hugues', null, '87-100-7912', 'jcridgea4@columbia.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (366, 'Neron', 'Pavia', null, '28-187-0862', 'nhanaforda5@yahoo.co.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (367, 'Willi', 'Rahlof', null, '59-487-9974', 'wposseka6@scribd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (368, 'Elizabet', 'Spilstead', 'Tremblay', '95-174-8974', 'etremblaya7@1und1.de', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (369, 'Zena', 'Jennaroy', null, '36-174-8394', 'zsketchleya8@nifty.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (370, 'Ivor', 'Thwaites', 'Paulot', '47-854-4738', 'ipaulota9@businessinsider.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (371, 'Trudie', 'McGavigan', 'Esmond', '22-324-9744', 'tesmondaa@samsung.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (372, 'Felipe', 'Coste', 'Officer', '83-603-3581', 'fofficerab@ox.ac.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (373, 'Jaimie', 'Demsey', 'Howsin', '62-183-5376', 'jhowsinac@gravatar.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (374, 'Vittorio', 'Cobbled', null, '14-533-5518', 'vclyburnad@flickr.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (375, 'Shawna', 'Barstock', 'Flude', '03-493-0631', 'sfludeae@google.pl', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (376, 'James', 'Dorkens', 'O''Towey', '93-682-2974', 'jotoweyaf@sina.com.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (377, 'Abbie', 'Wooler', 'Norree', '56-315-2684', 'anorreeag@51.la', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (378, 'Farlee', 'Gommowe', 'Eunson', '75-327-0139', 'feunsonah@nbcnews.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (379, 'Koren', 'Kibble', 'Swinfen', '99-991-9537', 'kswinfenai@uiuc.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (380, 'Siobhan', 'Swyre', 'Mabbutt', '87-254-4922', 'smabbuttaj@dailymail.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (381, 'Nat', 'McCaughren', 'Kilday', '49-239-6913', 'nkildayak@printfriendly.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (382, 'Ruthann', 'Bineham', 'Dodds', '56-327-3353', 'rdoddsal@xing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (383, 'Yard', 'Roman', 'Mazin', '31-285-1105', 'ymazinam@cafepress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (384, 'Thurstan', 'Roseaman', null, '88-745-5057', 'tpacean@csmonitor.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (385, 'Robena', 'Powis', 'McCroft', '03-470-1640', 'rmccroftao@smugmug.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (386, 'Raynor', 'Crawford', 'Rentalll', '98-785-7679', 'rrentalllap@statcounter.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (387, 'Tandy', 'Wartonby', null, '53-498-6954', 'thaversaq@mapy.cz', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (388, 'Win', 'Pitkaithly', null, '57-421-2936', 'wdawidowskyar@opensource.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (389, 'Emilia', 'Gadsby', 'Vernall', '61-568-7042', 'evernallas@abc.net.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (390, 'Violette', 'Asch', 'McBayne', '79-913-1024', 'vmcbayneat@utexas.edu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (391, 'Yurik', 'Thackray', 'Jaggard', '60-338-5085', 'yjaggardau@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (392, 'Merrie', 'McKern', 'Frost', '29-628-7087', 'mfrostav@ifeng.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (393, 'Rorke', 'Prandy', null, '82-909-9389', 'rcatanheiraaw@unesco.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (394, 'Alleen', 'Fothergill', 'Devonald', '78-482-2633', 'adevonaldax@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (395, 'Veronique', 'Suffe', 'Koche', '92-324-8758', 'vkocheay@elpais.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (396, 'Doralin', 'Constant', null, '88-685-6313', 'dackwoodaz@diigo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (397, 'Karrie', 'Khosa', 'Strawbridge', '73-944-8974', 'kstrawbridgeb0@ihg.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (398, 'Pavla', 'Atwater', 'Albasiny', '24-120-6130', 'palbasinyb1@simplemachines.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (399, 'Phineas', 'Dutt', 'Bulger', '22-758-8245', 'pbulgerb2@livejournal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (400, 'Ilyse', 'Weaben', 'Houlahan', '70-207-1655', 'ihoulahanb3@hhs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (401, 'Cicily', 'Berfoot', 'Woodfin', '70-614-1854', 'cwoodfinb4@hibu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (402, 'Conni', 'Mistry', 'Beumant', '43-923-1490', 'cbeumantb5@rediff.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (403, 'Briant', 'Jirik', 'Kirley', '19-240-2481', 'bkirleyb6@studiopress.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (404, 'Ellette', 'Loachhead', 'Zylbermann', '62-466-1969', 'ezylbermannb7@cloudflare.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (405, 'Kare', 'Wickersham', 'Uzzell', '93-990-0656', 'kuzzellb8@webeden.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (406, 'Bianca', 'Remer', null, '10-371-7404', 'bcordayb9@statcounter.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (407, 'Lolita', 'Shorland', 'Marklew', '34-391-6213', 'lmarklewba@shop-pro.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (408, 'Gilly', 'Buesnel', 'Quince', '38-586-5919', 'gquincebb@zdnet.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (409, 'Max', 'Blundell', 'Diloway', '28-805-1976', 'mdilowaybc@geocities.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (410, 'Fawnia', 'Latus', 'Siddall', '28-499-4018', 'fsiddallbd@noaa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (411, 'Lee', 'Dewey', 'Raraty', '67-869-7975', 'lraratybe@amazon.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (412, 'Jud', 'Resun', 'Swigger', '41-136-4770', 'jswiggerbf@canalblog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (413, 'Emmy', 'Hambridge', 'Garber', '93-046-9291', 'egarberbg@gnu.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (414, 'Alwyn', 'MacLaverty', 'Aizikovich', '24-222-9807', 'aaizikovichbh@xrea.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (415, 'Siusan', 'Biasioli', 'McRoberts', '38-272-2232', 'smcrobertsbi@dell.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (416, 'Balduin', 'Escala', 'Gresswell', '32-283-8726', 'bgresswellbj@gmpg.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (417, 'Jedd', 'Davidsson', 'Langsbury', '77-546-4386', 'jlangsburybk@tripod.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (418, 'Kaine', 'Hounson', 'Enrietto', '92-043-3199', 'kenriettobl@indiegogo.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (419, 'Udell', 'Keele', null, '47-766-4790', 'utassakerbm@weibo.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (420, 'Evvie', 'Alecock', 'Cranson', '98-955-9343', 'ecransonbn@i2i.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (421, 'Jenifer', 'Teal', 'Francomb', '80-553-2528', 'jfrancombbo@nhs.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (422, 'Evie', 'Reary', 'Frondt', '85-829-8280', 'efrondtbp@uiuc.edu', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (423, 'Ross', 'Benham', null, '22-394-9156', 'rhuddlebq@about.me', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (424, 'Peirce', 'Fenby', 'Leyes', '31-027-4473', 'pleyesbr@dropbox.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (425, 'Janie', 'Brimicombe', 'Hosten', '43-073-8106', 'jhostenbs@sina.com.cn', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (426, 'Alla', 'Locket', 'Stubbert', '93-682-9672', 'astubbertbt@ocn.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (427, 'Nikkie', 'Lemin', 'Bertholin', '39-614-9155', 'nbertholinbu@google.fr', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (428, 'Rose', 'Rappa', 'Christaeas', '72-608-2013', 'rchristaeasbv@admin.ch', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (429, 'Clarabelle', 'Barras', null, '03-202-8262', 'cmithambw@dot.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (430, 'Megan', 'Stouther', 'Swadden', '27-754-1266', 'mswaddenbx@bravesites.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (431, 'Carmelia', 'Morot', 'Doonican', '70-121-6605', 'cdoonicanby@jiathis.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (432, 'Vicky', 'Leap', 'Allsworth', '59-643-0798', 'vallsworthbz@a8.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (433, 'Bernadene', 'Casolla', null, '25-493-8029', 'bshimmansc0@github.io', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (434, 'Eadie', 'Kleinpeltz', 'Thornally', '08-984-8050', 'ethornallyc1@deliciousdays.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (435, 'Hester', 'Shillan', 'Limpertz', '74-778-0882', 'hlimpertzc2@hhs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (436, 'Nigel', 'Hasty', 'Cowburn', '22-573-8071', 'ncowburnc3@census.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (437, 'Sydney', 'Loadwick', 'Baish', '99-997-7833', 'sbaishc4@ehow.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (438, 'Goober', 'Welbeck', 'MacGibbon', '03-602-2649', 'gmacgibbonc5@unicef.org', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (439, 'Kathe', 'Garret', null, '08-027-5892', 'kdillestonc6@naver.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (440, 'Pooh', 'Smouten', 'Sobczak', '19-095-7005', 'psobczakc7@shop-pro.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (441, 'Rodina', 'Bonevant', 'Somerlie', '08-312-4818', 'rsomerliec8@quantcast.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (442, 'Cyb', 'Carless', null, '87-671-7701', 'cdriverc9@webs.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (443, 'Horatia', 'Dollard', 'Aked', '30-394-0766', 'hakedca@comsenz.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (444, 'Adair', 'Stannas', 'Courtney', '71-050-2042', 'acourtneycb@indiatimes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (445, 'Sharl', 'Bratt', 'Flewitt', '74-594-8609', 'sflewittcc@fda.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (446, 'Westbrooke', 'Batrim', null, '44-253-1261', 'wpraycd@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (447, 'Zulema', 'Garnsworthy', 'Lugg', '90-160-1848', 'zluggce@nasa.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (448, 'Gabriele', 'Stilliard', 'Nisen', '26-901-1966', 'gnisencf@ocn.ne.jp', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (449, 'Ianthe', 'Dench', 'Sadry', '18-917-6369', 'isadrycg@bing.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (450, 'Christian', 'Geelan', null, '31-669-7560', 'cgeeringch@godaddy.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (451, 'Codi', 'Nottle', 'Beckingham', '04-967-5301', 'cbeckinghamci@blog.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (452, 'Don', 'Zamboniari', 'Start', '92-651-5766', 'dstartcj@noaa.gov', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (453, 'Nichole', 'Fedorski', null, '81-344-4081', 'ngofordck@live.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (454, 'Harmonie', 'Lacelett', null, '70-203-9330', 'hboobiercl@smugmug.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (455, 'Mick', 'McKeller', 'Yeowell', '22-698-2083', 'myeowellcm@imdb.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (456, 'Shanta', 'Le Grove', 'Niece', '55-150-3898', 'sniececn@dion.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (457, 'Minnie', 'Normandale', null, '25-249-8932', 'mjeppensenco@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (458, 'Kayle', 'Cockell', null, '73-346-8868', 'kpalkecp@timesonline.co.uk', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (459, 'Yancey', 'Elt', 'Ballantyne', '18-617-1401', 'yballantynecq@privacy.gov.au', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (460, 'Aura', 'De Ferraris', null, '20-142-2928', 'astoadecr@skyrock.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (461, 'Glory', 'Giacoppoli', 'Janowicz', '21-322-5716', 'gjanowiczcs@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (462, 'Donny', 'Dasent', 'Nunson', '96-417-0601', 'dnunsonct@t-online.de', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (463, 'Fidole', 'Casperri', 'Dowzell', '52-654-9411', 'fdowzellcu@miitbeian.gov.cn', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (464, 'Carolann', 'McKomb', 'Falconbridge', '69-664-8102', 'cfalconbridgecv@intel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (465, 'Weidar', 'Murfett', 'Paz', '66-215-0081', 'wpazcw@elegantthemes.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (466, 'Christophe', 'Cussen', 'Riccione', '59-615-9926', 'criccionecx@irs.gov', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (467, 'Harmonie', 'Avrahamian', 'Botcherby', '14-770-4585', 'hbotcherbycy@yellowpages.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (468, 'Eddie', 'Moffatt', null, '34-770-9190', 'egorvincz@elegantthemes.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (469, 'Norton', 'Dossit', 'Halpin', '49-322-0293', 'nhalpind0@europa.eu', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (470, 'Chrystel', 'Korejs', 'Elleray', '88-527-4497', 'cellerayd1@issuu.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (471, 'Lisle', 'Rishworth', 'Scheffel', '43-158-3199', 'lscheffeld2@gravatar.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (472, 'Gualterio', 'Levis', 'Livesay', '65-266-5436', 'glivesayd3@fotki.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (473, 'Lilla', 'Rishman', 'Ollis', '87-913-1766', 'lollisd4@newsvine.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (474, 'Menard', 'Bento', null, '11-768-6476', 'mbiasettid5@shareasale.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (475, 'Lenard', 'Pane', null, '12-644-1941', 'lrouged6@huffingtonpost.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (476, 'Gallagher', 'McNeice', 'Brinkman', '68-747-0213', 'gbrinkmand7@sbwire.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (477, 'Carolin', 'Wilgar', null, '05-616-2434', 'cmacfarland8@odnoklassniki.ru', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (478, 'Norri', 'Capelen', null, '73-349-1712', 'npurdeyd9@bigcartel.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (479, 'Juditha', 'Rickersey', 'Mapes', '42-972-2092', 'jmapesda@hao123.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (480, 'Clemmy', 'Soame', null, '83-912-6210', 'cfordydb@guardian.co.uk', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (481, 'Lin', 'Taffee', 'Spillane', '54-517-7185', 'lspillanedc@storify.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (482, 'Emlynn', 'Serrurier', 'Thoma', '72-064-0792', 'ethomadd@tuttocitta.it', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (483, 'Ruthe', 'Jacop', null, '19-632-9951', 'rraundde@stumbleupon.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (484, 'Marabel', 'Igo', 'Van der Beken', '56-593-7727', 'mvanderbekendf@sciencedirect.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (485, 'Torie', 'Fone', 'McPherson', '58-140-0028', 'tmcphersondg@blog.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (486, 'Eadie', 'Roostan', 'Chastey', '73-808-0186', 'echasteydh@xing.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (487, 'Almeria', 'Ballinger', null, '77-508-0123', 'ahazeltinedi@earthlink.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (488, 'Rodge', 'Gobbet', null, '17-626-2292', 'rdymokedj@scribd.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (489, 'Tamma', 'Morot', 'Cosbey', '65-967-4105', 'tcosbeydk@instagram.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (490, 'Maurie', 'Ruck', null, '44-247-9806', 'mdatedl@parallels.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (491, 'Barton', 'Ketteridge', 'Merwede', '69-600-0727', 'bmerwededm@dion.ne.jp', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (492, 'Florie', 'Gouldeby', 'Cordeux', '48-954-6973', 'fcordeuxdn@dyndns.org', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (493, 'Row', 'Hambly', 'McCaughren', '68-921-9837', 'rmccaughrendo@livejournal.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (494, 'Jens', 'Lynock', 'Whittlesee', '13-653-3483', 'jwhittleseedp@topsy.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (495, 'Lew', 'Attridge', null, '10-780-3870', 'lungerechtsdq@phpbb.com', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (496, 'Fernando', 'Matussow', null, '28-106-1349', 'fadelmandr@cpanel.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (497, 'Phyllys', 'Dami', null, '18-666-0538', 'peagellds@furl.net', floor(dbms_random.value(1,(select max(cliente_id) from cliente))));
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (498, 'Reggis', 'Dawidowicz', 'Erskin', '89-134-9398', 'rerskindt@examiner.com', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (499, 'Gleda', 'Tattershaw', null, '93-044-1317', 'gchaplyndu@seesaa.net', null);
insert into CLIENTE (cliente_id, nombre, ap_pat, ap_mat, rfc, email, aval_cliente_id) values (500, 'Dave', 'Filipczak', 'Leadbetter', '10-816-6903', 'dleadbetterdv@mapquest.com', null);
